//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace RWAS.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DS_Rep_SurveyMonthy")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_Rep_SurveyMonthy : System.Data.DataSet {
        
        private Rws_Sp_Rep_SurveyMonthy4DSDataTable tableRws_Sp_Rep_SurveyMonthy4DS;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_Rep_SurveyMonthy() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_Rep_SurveyMonthy(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Rws_Sp_Rep_SurveyMonthy4DS"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_SurveyMonthy4DSDataTable(ds.Tables["Rws_Sp_Rep_SurveyMonthy4DS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Rws_Sp_Rep_SurveyMonthy4DSDataTable Rws_Sp_Rep_SurveyMonthy4DS {
            get {
                return this.tableRws_Sp_Rep_SurveyMonthy4DS;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DS_Rep_SurveyMonthy cln = ((DS_Rep_SurveyMonthy)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Rws_Sp_Rep_SurveyMonthy4DS"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_SurveyMonthy4DSDataTable(ds.Tables["Rws_Sp_Rep_SurveyMonthy4DS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRws_Sp_Rep_SurveyMonthy4DS = ((Rws_Sp_Rep_SurveyMonthy4DSDataTable)(base.Tables["Rws_Sp_Rep_SurveyMonthy4DS"]));
            if ((initTable == true)) {
                if ((this.tableRws_Sp_Rep_SurveyMonthy4DS != null)) {
                    this.tableRws_Sp_Rep_SurveyMonthy4DS.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_Rep_SurveyMonthy";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_Rep_SurveyMonthy.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRws_Sp_Rep_SurveyMonthy4DS = new Rws_Sp_Rep_SurveyMonthy4DSDataTable();
            base.Tables.Add(this.tableRws_Sp_Rep_SurveyMonthy4DS);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRws_Sp_Rep_SurveyMonthy4DS() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DS_Rep_SurveyMonthy ds = new DS_Rep_SurveyMonthy();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void Rws_Sp_Rep_SurveyMonthy4DSRowChangeEventHandler(object sender, Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Rws_Sp_Rep_SurveyMonthy4DSDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnDayDate;
            
            private System.Data.DataColumn columnRws_Fld_fk_SurveyMajorItem;
            
            private System.Data.DataColumn columnRws_Fld_Describe;
            
            private System.Data.DataColumn columnF01;
            
            private System.Data.DataColumn columnF02;
            
            private System.Data.DataColumn columnF03;
            
            private System.Data.DataColumn columnF04;
            
            private System.Data.DataColumn columnF05;
            
            private System.Data.DataColumn columnF06;
            
            private System.Data.DataColumn columnF07;
            
            private System.Data.DataColumn columnF08;
            
            private System.Data.DataColumn columnF09;
            
            private System.Data.DataColumn columnF10;
            
            private System.Data.DataColumn columnF11;
            
            private System.Data.DataColumn columnF12;
            
            private System.Data.DataColumn columnsum;
            
            private System.Data.DataColumn columnpercent;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_SurveyMonthy4DSDataTable() {
                this.TableName = "Rws_Sp_Rep_SurveyMonthy4DS";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_SurveyMonthy4DSDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Rws_Sp_Rep_SurveyMonthy4DSDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn DayDateColumn {
                get {
                    return this.columnDayDate;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_fk_SurveyMajorItemColumn {
                get {
                    return this.columnRws_Fld_fk_SurveyMajorItem;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DescribeColumn {
                get {
                    return this.columnRws_Fld_Describe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F01Column {
                get {
                    return this.columnF01;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F02Column {
                get {
                    return this.columnF02;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F03Column {
                get {
                    return this.columnF03;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F04Column {
                get {
                    return this.columnF04;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F05Column {
                get {
                    return this.columnF05;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F06Column {
                get {
                    return this.columnF06;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F07Column {
                get {
                    return this.columnF07;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F08Column {
                get {
                    return this.columnF08;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F09Column {
                get {
                    return this.columnF09;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F10Column {
                get {
                    return this.columnF10;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F11Column {
                get {
                    return this.columnF11;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn F12Column {
                get {
                    return this.columnF12;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn sumColumn {
                get {
                    return this.columnsum;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn percentColumn {
                get {
                    return this.columnpercent;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_SurveyMonthy4DSRow this[int index] {
                get {
                    return ((Rws_Sp_Rep_SurveyMonthy4DSRow)(this.Rows[index]));
                }
            }
            
            public event Rws_Sp_Rep_SurveyMonthy4DSRowChangeEventHandler Rws_Sp_Rep_SurveyMonthy4DSRowChanging;
            
            public event Rws_Sp_Rep_SurveyMonthy4DSRowChangeEventHandler Rws_Sp_Rep_SurveyMonthy4DSRowChanged;
            
            public event Rws_Sp_Rep_SurveyMonthy4DSRowChangeEventHandler Rws_Sp_Rep_SurveyMonthy4DSRowDeleting;
            
            public event Rws_Sp_Rep_SurveyMonthy4DSRowChangeEventHandler Rws_Sp_Rep_SurveyMonthy4DSRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRws_Sp_Rep_SurveyMonthy4DSRow(Rws_Sp_Rep_SurveyMonthy4DSRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_SurveyMonthy4DSRow AddRws_Sp_Rep_SurveyMonthy4DSRow(
                        string DayDate, 
                        byte Rws_Fld_fk_SurveyMajorItem, 
                        string Rws_Fld_Describe, 
                        int F01, 
                        int F02, 
                        int F03, 
                        int F04, 
                        int F05, 
                        int F06, 
                        int F07, 
                        int F08, 
                        int F09, 
                        int F10, 
                        int F11, 
                        int F12, 
                        int sum, 
                        decimal percent) {
                Rws_Sp_Rep_SurveyMonthy4DSRow rowRws_Sp_Rep_SurveyMonthy4DSRow = ((Rws_Sp_Rep_SurveyMonthy4DSRow)(this.NewRow()));
                rowRws_Sp_Rep_SurveyMonthy4DSRow.ItemArray = new object[] {
                        DayDate,
                        Rws_Fld_fk_SurveyMajorItem,
                        Rws_Fld_Describe,
                        F01,
                        F02,
                        F03,
                        F04,
                        F05,
                        F06,
                        F07,
                        F08,
                        F09,
                        F10,
                        F11,
                        F12,
                        sum,
                        percent};
                this.Rows.Add(rowRws_Sp_Rep_SurveyMonthy4DSRow);
                return rowRws_Sp_Rep_SurveyMonthy4DSRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                Rws_Sp_Rep_SurveyMonthy4DSDataTable cln = ((Rws_Sp_Rep_SurveyMonthy4DSDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new Rws_Sp_Rep_SurveyMonthy4DSDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnDayDate = base.Columns["DayDate"];
                this.columnRws_Fld_fk_SurveyMajorItem = base.Columns["Rws_Fld_fk_SurveyMajorItem"];
                this.columnRws_Fld_Describe = base.Columns["Rws_Fld_Describe"];
                this.columnF01 = base.Columns["F01"];
                this.columnF02 = base.Columns["F02"];
                this.columnF03 = base.Columns["F03"];
                this.columnF04 = base.Columns["F04"];
                this.columnF05 = base.Columns["F05"];
                this.columnF06 = base.Columns["F06"];
                this.columnF07 = base.Columns["F07"];
                this.columnF08 = base.Columns["F08"];
                this.columnF09 = base.Columns["F09"];
                this.columnF10 = base.Columns["F10"];
                this.columnF11 = base.Columns["F11"];
                this.columnF12 = base.Columns["F12"];
                this.columnsum = base.Columns["sum"];
                this.columnpercent = base.Columns["percent"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnDayDate = new System.Data.DataColumn("DayDate", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnDayDate);
                this.columnRws_Fld_fk_SurveyMajorItem = new System.Data.DataColumn("Rws_Fld_fk_SurveyMajorItem", typeof(byte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_fk_SurveyMajorItem);
                this.columnRws_Fld_Describe = new System.Data.DataColumn("Rws_Fld_Describe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Describe);
                this.columnF01 = new System.Data.DataColumn("F01", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF01);
                this.columnF02 = new System.Data.DataColumn("F02", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF02);
                this.columnF03 = new System.Data.DataColumn("F03", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF03);
                this.columnF04 = new System.Data.DataColumn("F04", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF04);
                this.columnF05 = new System.Data.DataColumn("F05", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF05);
                this.columnF06 = new System.Data.DataColumn("F06", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF06);
                this.columnF07 = new System.Data.DataColumn("F07", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF07);
                this.columnF08 = new System.Data.DataColumn("F08", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF08);
                this.columnF09 = new System.Data.DataColumn("F09", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF09);
                this.columnF10 = new System.Data.DataColumn("F10", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF10);
                this.columnF11 = new System.Data.DataColumn("F11", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF11);
                this.columnF12 = new System.Data.DataColumn("F12", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnF12);
                this.columnsum = new System.Data.DataColumn("sum", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnsum);
                this.columnpercent = new System.Data.DataColumn("percent", typeof(decimal), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnpercent);
                this.columnDayDate.ReadOnly = true;
                this.columnRws_Fld_fk_SurveyMajorItem.AllowDBNull = false;
                this.columnRws_Fld_fk_SurveyMajorItem.ReadOnly = true;
                this.columnRws_Fld_Describe.AllowDBNull = false;
                this.columnF01.ReadOnly = true;
                this.columnF02.ReadOnly = true;
                this.columnF03.ReadOnly = true;
                this.columnF04.ReadOnly = true;
                this.columnF05.ReadOnly = true;
                this.columnF06.ReadOnly = true;
                this.columnF07.ReadOnly = true;
                this.columnF08.ReadOnly = true;
                this.columnF09.ReadOnly = true;
                this.columnF10.ReadOnly = true;
                this.columnF11.ReadOnly = true;
                this.columnF12.ReadOnly = true;
                this.columnsum.ReadOnly = true;
                this.columnpercent.ReadOnly = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_SurveyMonthy4DSRow NewRws_Sp_Rep_SurveyMonthy4DSRow() {
                return ((Rws_Sp_Rep_SurveyMonthy4DSRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new Rws_Sp_Rep_SurveyMonthy4DSRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(Rws_Sp_Rep_SurveyMonthy4DSRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Rws_Sp_Rep_SurveyMonthy4DSRowChanged != null)) {
                    this.Rws_Sp_Rep_SurveyMonthy4DSRowChanged(this, new Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent(((Rws_Sp_Rep_SurveyMonthy4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Rws_Sp_Rep_SurveyMonthy4DSRowChanging != null)) {
                    this.Rws_Sp_Rep_SurveyMonthy4DSRowChanging(this, new Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent(((Rws_Sp_Rep_SurveyMonthy4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Rws_Sp_Rep_SurveyMonthy4DSRowDeleted != null)) {
                    this.Rws_Sp_Rep_SurveyMonthy4DSRowDeleted(this, new Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent(((Rws_Sp_Rep_SurveyMonthy4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Rws_Sp_Rep_SurveyMonthy4DSRowDeleting != null)) {
                    this.Rws_Sp_Rep_SurveyMonthy4DSRowDeleting(this, new Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent(((Rws_Sp_Rep_SurveyMonthy4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRws_Sp_Rep_SurveyMonthy4DSRow(Rws_Sp_Rep_SurveyMonthy4DSRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DS_Rep_SurveyMonthy ds = new DS_Rep_SurveyMonthy();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Rws_Sp_Rep_SurveyMonthy4DSDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Rws_Sp_Rep_SurveyMonthy4DSRow : System.Data.DataRow {
            
            private Rws_Sp_Rep_SurveyMonthy4DSDataTable tableRws_Sp_Rep_SurveyMonthy4DS;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_SurveyMonthy4DSRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRws_Sp_Rep_SurveyMonthy4DS = ((Rws_Sp_Rep_SurveyMonthy4DSDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DayDate {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.DayDateColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'DayDate\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.DayDateColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Rws_Fld_fk_SurveyMajorItem {
                get {
                    return ((byte)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.Rws_Fld_fk_SurveyMajorItemColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.Rws_Fld_fk_SurveyMajorItemColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_Describe {
                get {
                    return ((string)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.Rws_Fld_DescribeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.Rws_Fld_DescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F01 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F01Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F01\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F01Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F02 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F02Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F02\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F02Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F03 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F03Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F03\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F03Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F04 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F04Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F04\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F04Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F05 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F05Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F05\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F05Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F06 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F06Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F06\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F06Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F07 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F07Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F07\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F07Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F08 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F08Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F08\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F08Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F09 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F09Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F09\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F09Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F10 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F10Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F10\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F10Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F11 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F11Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F11\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F11Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int F12 {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F12Column]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'F12\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F12Column] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int sum {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.sumColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'sum\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.sumColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal percent {
                get {
                    try {
                        return ((decimal)(this[this.tableRws_Sp_Rep_SurveyMonthy4DS.percentColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'percent\' in table \'Rws_Sp_Rep_SurveyMonthy4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_SurveyMonthy4DS.percentColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDayDateNull() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.DayDateColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDayDateNull() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.DayDateColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF01Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F01Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF01Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F01Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF02Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F02Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF02Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F02Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF03Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F03Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF03Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F03Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF04Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F04Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF04Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F04Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF05Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F05Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF05Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F05Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF06Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F06Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF06Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F06Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF07Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F07Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF07Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F07Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF08Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F08Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF08Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F08Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF09Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F09Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF09Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F09Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF10Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F10Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF10Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F10Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF11Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F11Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF11Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F11Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsF12Null() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.F12Column);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetF12Null() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.F12Column] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IssumNull() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.sumColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetsumNull() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.sumColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IspercentNull() {
                return this.IsNull(this.tableRws_Sp_Rep_SurveyMonthy4DS.percentColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetpercentNull() {
                this[this.tableRws_Sp_Rep_SurveyMonthy4DS.percentColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent : System.EventArgs {
            
            private Rws_Sp_Rep_SurveyMonthy4DSRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_SurveyMonthy4DSRowChangeEvent(Rws_Sp_Rep_SurveyMonthy4DSRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_SurveyMonthy4DSRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591