//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace RWAS.Common
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;


    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class DS_Personel : DataSet
    {

        private Prs_Sp_Sel_PersonelDataTable tablePrs_Sp_Sel_Personel;

        public DS_Personel()
        {
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }

        protected DS_Personel(SerializationInfo info, StreamingContext context)
        {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null))
            {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Prs_Sp_Sel_Personel"] != null))
                {
                    this.Tables.Add(new Prs_Sp_Sel_PersonelDataTable(ds.Tables["Prs_Sp_Sel_Personel"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else
            {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }

        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Prs_Sp_Sel_PersonelDataTable Prs_Sp_Sel_Personel
        {
            get
            {
                return this.tablePrs_Sp_Sel_Personel;
            }
        }

        public override DataSet Clone()
        {
            DS_Personel cln = ((DS_Personel)(base.Clone()));
            cln.InitVars();
            return cln;
        }

        protected override bool ShouldSerializeTables()
        {
            return false;
        }

        protected override bool ShouldSerializeRelations()
        {
            return false;
        }

        protected override void ReadXmlSerializable(XmlReader reader)
        {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Prs_Sp_Sel_Personel"] != null))
            {
                this.Tables.Add(new Prs_Sp_Sel_PersonelDataTable(ds.Tables["Prs_Sp_Sel_Personel"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }

        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable()
        {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }

        internal void InitVars()
        {
            this.tablePrs_Sp_Sel_Personel = ((Prs_Sp_Sel_PersonelDataTable)(this.Tables["Prs_Sp_Sel_Personel"]));
            if ((this.tablePrs_Sp_Sel_Personel != null))
            {
                this.tablePrs_Sp_Sel_Personel.InitVars();
            }
        }

        private void InitClass()
        {
            this.DataSetName = "DS_Personel";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_Personel.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tablePrs_Sp_Sel_Personel = new Prs_Sp_Sel_PersonelDataTable();
            this.Tables.Add(this.tablePrs_Sp_Sel_Personel);
        }

        private bool ShouldSerializePrs_Sp_Sel_Personel()
        {
            return false;
        }

        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e)
        {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove))
            {
                this.InitVars();
            }
        }

        public delegate void Prs_Sp_Sel_PersonelRowChangeEventHandler(object sender, Prs_Sp_Sel_PersonelRowChangeEvent e);

        [System.Diagnostics.DebuggerStepThrough()]
        public class Prs_Sp_Sel_PersonelDataTable : DataTable, System.Collections.IEnumerable
        {

            private DataColumn columnPrs_Fld_UniqueCode;

            private DataColumn columnPrs_Fld_PersonelID;

            private DataColumn columnPrs_Fld_PersonelID_Org;

            private DataColumn columnPrs_Fld_FirstName;

            private DataColumn columnPrs_Fld_FirstName_Org;

            private DataColumn columnPrs_Fld_LastName;

            private DataColumn columnPrs_Fld_LastName_Org;

            private DataColumn columnPrs_Fld_FullName;

            private DataColumn columnPrs_Fld_FatherName;

            private DataColumn columnPrs_Fld_FatherName_Org;

            private DataColumn columnPrs_Fld_IDNo;

            private DataColumn columnPrs_Fld_IDNo_Org;

            private DataColumn columnPrs_Fld_MaritalStatus;

            private DataColumn columnPrs_Fld_MaritalStatus_Org;

            private DataColumn columnPrs_Fld_fk_Job;

            private DataColumn columnPrs_Fld_JobDescribe;

            private DataColumn columnPrs_Fld_fk_Job_Org;

            private DataColumn columnPrs_Fld_fk_Job2;

            private DataColumn columnPrs_Fld_fk_Job2_Org;

            private DataColumn columnPrs_Fld_JobHistory;

            private DataColumn columnPrs_Fld_JobHistory_Org;

            private DataColumn columnPrs_Fld_LastJobHistory;

            private DataColumn columnPrs_Fld_LastJobHistory_Org;

            private DataColumn columnPrs_Fld_BirthYear;

            private DataColumn columnPrs_Fld_BirthYear_Org;

            private DataColumn columnPrs_Fld_fk_StudyStatus;

            private DataColumn columnPrs_Fld_fk_StudyStatus_Org;

            private DataColumn columnPrs_Fld_fk_EmployeeStatus;

            private DataColumn columnPrs_Fld_fk_EmployeeStatus_Org;

            private DataColumn columnPrs_Fld_EmployeeDate;

            private DataColumn columnPrs_Fld_EmployeeDate_Org;

            private DataColumn columnPrs_Fld_Address;

            private DataColumn columnPrs_Fld_TelNo;

            private DataColumn columnPrs_Fld_fk_OrgUnit;

            private DataColumn columnPrs_Fld_fk_Region;

            private DataColumn columnPrs_Fld_RegionDescribe;

            private DataColumn columnPrs_Fld_fk_SubContractor;

            private DataColumn columnPrs_Fld_Contractor;

            internal Prs_Sp_Sel_PersonelDataTable()
                :
                    base("Prs_Sp_Sel_Personel")
            {
                this.InitClass();
            }

            internal Prs_Sp_Sel_PersonelDataTable(DataTable table)
                :
                    base(table.TableName)
            {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive))
                {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString()))
                {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace))
                {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }

            [System.ComponentModel.Browsable(false)]
            public int Count
            {
                get
                {
                    return this.Rows.Count;
                }
            }

            internal DataColumn Prs_Fld_UniqueCodeColumn
            {
                get
                {
                    return this.columnPrs_Fld_UniqueCode;
                }
            }

            internal DataColumn Prs_Fld_PersonelIDColumn
            {
                get
                {
                    return this.columnPrs_Fld_PersonelID;
                }
            }

            internal DataColumn Prs_Fld_PersonelID_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_PersonelID_Org;
                }
            }

            internal DataColumn Prs_Fld_FirstNameColumn
            {
                get
                {
                    return this.columnPrs_Fld_FirstName;
                }
            }

            internal DataColumn Prs_Fld_FirstName_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_FirstName_Org;
                }
            }

            internal DataColumn Prs_Fld_LastNameColumn
            {
                get
                {
                    return this.columnPrs_Fld_LastName;
                }
            }

            internal DataColumn Prs_Fld_LastName_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_LastName_Org;
                }
            }

            internal DataColumn Prs_Fld_FullNameColumn
            {
                get
                {
                    return this.columnPrs_Fld_FullName;
                }
            }

            internal DataColumn Prs_Fld_FatherNameColumn
            {
                get
                {
                    return this.columnPrs_Fld_FatherName;
                }
            }

            internal DataColumn Prs_Fld_FatherName_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_FatherName_Org;
                }
            }

            internal DataColumn Prs_Fld_IDNoColumn
            {
                get
                {
                    return this.columnPrs_Fld_IDNo;
                }
            }

            internal DataColumn Prs_Fld_IDNo_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_IDNo_Org;
                }
            }

            internal DataColumn Prs_Fld_MaritalStatusColumn
            {
                get
                {
                    return this.columnPrs_Fld_MaritalStatus;
                }
            }

            internal DataColumn Prs_Fld_MaritalStatus_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_MaritalStatus_Org;
                }
            }

            internal DataColumn Prs_Fld_fk_JobColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_Job;
                }
            }

            internal DataColumn Prs_Fld_JobDescribeColumn
            {
                get
                {
                    return this.columnPrs_Fld_JobDescribe;
                }
            }

            internal DataColumn Prs_Fld_fk_Job_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_Job_Org;
                }
            }

            internal DataColumn Prs_Fld_fk_Job2Column
            {
                get
                {
                    return this.columnPrs_Fld_fk_Job2;
                }
            }

            internal DataColumn Prs_Fld_fk_Job2_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_Job2_Org;
                }
            }

            internal DataColumn Prs_Fld_JobHistoryColumn
            {
                get
                {
                    return this.columnPrs_Fld_JobHistory;
                }
            }

            internal DataColumn Prs_Fld_JobHistory_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_JobHistory_Org;
                }
            }

            internal DataColumn Prs_Fld_LastJobHistoryColumn
            {
                get
                {
                    return this.columnPrs_Fld_LastJobHistory;
                }
            }

            internal DataColumn Prs_Fld_LastJobHistory_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_LastJobHistory_Org;
                }
            }

            internal DataColumn Prs_Fld_BirthYearColumn
            {
                get
                {
                    return this.columnPrs_Fld_BirthYear;
                }
            }

            internal DataColumn Prs_Fld_BirthYear_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_BirthYear_Org;
                }
            }

            internal DataColumn Prs_Fld_fk_StudyStatusColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_StudyStatus;
                }
            }

            internal DataColumn Prs_Fld_fk_StudyStatus_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_StudyStatus_Org;
                }
            }

            internal DataColumn Prs_Fld_fk_EmployeeStatusColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_EmployeeStatus;
                }
            }

            internal DataColumn Prs_Fld_fk_EmployeeStatus_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_EmployeeStatus_Org;
                }
            }

            internal DataColumn Prs_Fld_EmployeeDateColumn
            {
                get
                {
                    return this.columnPrs_Fld_EmployeeDate;
                }
            }

            internal DataColumn Prs_Fld_EmployeeDate_OrgColumn
            {
                get
                {
                    return this.columnPrs_Fld_EmployeeDate_Org;
                }
            }

            internal DataColumn Prs_Fld_AddressColumn
            {
                get
                {
                    return this.columnPrs_Fld_Address;
                }
            }

            internal DataColumn Prs_Fld_TelNoColumn
            {
                get
                {
                    return this.columnPrs_Fld_TelNo;
                }
            }

            internal DataColumn Prs_Fld_fk_OrgUnitColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_OrgUnit;
                }
            }

            internal DataColumn Prs_Fld_fk_RegionColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_Region;
                }
            }

            internal DataColumn Prs_Fld_RegionDescribeColumn
            {
                get
                {
                    return this.columnPrs_Fld_RegionDescribe;
                }
            }

            internal DataColumn Prs_Fld_fk_SubContractorColumn
            {
                get
                {
                    return this.columnPrs_Fld_fk_SubContractor;
                }
            }

            internal DataColumn Prs_Fld_ContractorColumn
            {
                get
                {
                    return this.columnPrs_Fld_Contractor;
                }
            }

            public Prs_Sp_Sel_PersonelRow this[int index]
            {
                get
                {
                    return ((Prs_Sp_Sel_PersonelRow)(this.Rows[index]));
                }
            }

            public event Prs_Sp_Sel_PersonelRowChangeEventHandler Prs_Sp_Sel_PersonelRowChanged;

            public event Prs_Sp_Sel_PersonelRowChangeEventHandler Prs_Sp_Sel_PersonelRowChanging;

            public event Prs_Sp_Sel_PersonelRowChangeEventHandler Prs_Sp_Sel_PersonelRowDeleted;

            public event Prs_Sp_Sel_PersonelRowChangeEventHandler Prs_Sp_Sel_PersonelRowDeleting;

            public void AddPrs_Sp_Sel_PersonelRow(Prs_Sp_Sel_PersonelRow row)
            {
                this.Rows.Add(row);
            }

            public Prs_Sp_Sel_PersonelRow AddPrs_Sp_Sel_PersonelRow(
                        int Prs_Fld_UniqueCode,
                        int Prs_Fld_PersonelID,
                        bool Prs_Fld_PersonelID_Org,
                        string Prs_Fld_FirstName,
                        bool Prs_Fld_FirstName_Org,
                        string Prs_Fld_LastName,
                        bool Prs_Fld_LastName_Org,
                        string Prs_Fld_FullName,
                        string Prs_Fld_FatherName,
                        bool Prs_Fld_FatherName_Org,
                        int Prs_Fld_IDNo,
                        bool Prs_Fld_IDNo_Org,
                        byte Prs_Fld_MaritalStatus,
                        bool Prs_Fld_MaritalStatus_Org,
                        string Prs_Fld_fk_Job,
                        string Prs_Fld_JobDescribe,
                        bool Prs_Fld_fk_Job_Org,
                        string Prs_Fld_fk_Job2,
                        bool Prs_Fld_fk_Job2_Org,
                        short Prs_Fld_JobHistory,
                        bool Prs_Fld_JobHistory_Org,
                        short Prs_Fld_LastJobHistory,
                        bool Prs_Fld_LastJobHistory_Org,
                        short Prs_Fld_BirthYear,
                        bool Prs_Fld_BirthYear_Org,
                        short Prs_Fld_fk_StudyStatus,
                        bool Prs_Fld_fk_StudyStatus_Org,
                        System.Byte Prs_Fld_fk_EmployeeStatus,
                        bool Prs_Fld_fk_EmployeeStatus_Org,
                        string Prs_Fld_EmployeeDate,
                        bool Prs_Fld_EmployeeDate_Org,
                        string Prs_Fld_Address,
                        string Prs_Fld_TelNo,
                        int Prs_Fld_fk_OrgUnit,
                        int Prs_Fld_fk_Region,
                        string Prs_Fld_RegionDescribe,
                        int Prs_Fld_fk_SubContractor,
                        string Prs_Fld_Contractor)
            {
                Prs_Sp_Sel_PersonelRow rowPrs_Sp_Sel_PersonelRow = ((Prs_Sp_Sel_PersonelRow)(this.NewRow()));
                rowPrs_Sp_Sel_PersonelRow.ItemArray = new object[] {
                        Prs_Fld_UniqueCode,
                        Prs_Fld_PersonelID,
                        Prs_Fld_PersonelID_Org,
                        Prs_Fld_FirstName,
                        Prs_Fld_FirstName_Org,
                        Prs_Fld_LastName,
                        Prs_Fld_LastName_Org,
                        Prs_Fld_FullName,
                        Prs_Fld_FatherName,
                        Prs_Fld_FatherName_Org,
                        Prs_Fld_IDNo,
                        Prs_Fld_IDNo_Org,
                        Prs_Fld_MaritalStatus,
                        Prs_Fld_MaritalStatus_Org,
                        Prs_Fld_fk_Job,
                        Prs_Fld_JobDescribe,
                        Prs_Fld_fk_Job_Org,
                        Prs_Fld_fk_Job2,
                        Prs_Fld_fk_Job2_Org,
                        Prs_Fld_JobHistory,
                        Prs_Fld_JobHistory_Org,
                        Prs_Fld_LastJobHistory,
                        Prs_Fld_LastJobHistory_Org,
                        Prs_Fld_BirthYear,
                        Prs_Fld_BirthYear_Org,
                        Prs_Fld_fk_StudyStatus,
                        Prs_Fld_fk_StudyStatus_Org,
                        Prs_Fld_fk_EmployeeStatus,
                        Prs_Fld_fk_EmployeeStatus_Org,
                        Prs_Fld_EmployeeDate,
                        Prs_Fld_EmployeeDate_Org,
                        Prs_Fld_Address,
                        Prs_Fld_TelNo,
                        Prs_Fld_fk_OrgUnit,
                        Prs_Fld_fk_Region,
                        Prs_Fld_RegionDescribe,
                        Prs_Fld_fk_SubContractor,
                        Prs_Fld_Contractor};
                this.Rows.Add(rowPrs_Sp_Sel_PersonelRow);
                return rowPrs_Sp_Sel_PersonelRow;
            }

            public System.Collections.IEnumerator GetEnumerator()
            {
                return this.Rows.GetEnumerator();
            }

            public override DataTable Clone()
            {
                Prs_Sp_Sel_PersonelDataTable cln = ((Prs_Sp_Sel_PersonelDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }

            protected override DataTable CreateInstance()
            {
                return new Prs_Sp_Sel_PersonelDataTable();
            }

            internal void InitVars()
            {
                this.columnPrs_Fld_UniqueCode = this.Columns["Prs_Fld_UniqueCode"];
                this.columnPrs_Fld_PersonelID = this.Columns["Prs_Fld_PersonelID"];
                this.columnPrs_Fld_PersonelID_Org = this.Columns["Prs_Fld_PersonelID_Org"];
                this.columnPrs_Fld_FirstName = this.Columns["Prs_Fld_FirstName"];
                this.columnPrs_Fld_FirstName_Org = this.Columns["Prs_Fld_FirstName_Org"];
                this.columnPrs_Fld_LastName = this.Columns["Prs_Fld_LastName"];
                this.columnPrs_Fld_LastName_Org = this.Columns["Prs_Fld_LastName_Org"];
                this.columnPrs_Fld_FullName = this.Columns["Prs_Fld_FullName"];
                this.columnPrs_Fld_FatherName = this.Columns["Prs_Fld_FatherName"];
                this.columnPrs_Fld_FatherName_Org = this.Columns["Prs_Fld_FatherName_Org"];
                this.columnPrs_Fld_IDNo = this.Columns["Prs_Fld_IDNo"];
                this.columnPrs_Fld_IDNo_Org = this.Columns["Prs_Fld_IDNo_Org"];
                this.columnPrs_Fld_MaritalStatus = this.Columns["Prs_Fld_MaritalStatus"];
                this.columnPrs_Fld_MaritalStatus_Org = this.Columns["Prs_Fld_MaritalStatus_Org"];
                this.columnPrs_Fld_fk_Job = this.Columns["Prs_Fld_fk_Job"];
                this.columnPrs_Fld_JobDescribe = this.Columns["Prs_Fld_JobDescribe"];
                this.columnPrs_Fld_fk_Job_Org = this.Columns["Prs_Fld_fk_Job_Org"];
                this.columnPrs_Fld_fk_Job2 = this.Columns["Prs_Fld_fk_Job2"];
                this.columnPrs_Fld_fk_Job2_Org = this.Columns["Prs_Fld_fk_Job2_Org"];
                this.columnPrs_Fld_JobHistory = this.Columns["Prs_Fld_JobHistory"];
                this.columnPrs_Fld_JobHistory_Org = this.Columns["Prs_Fld_JobHistory_Org"];
                this.columnPrs_Fld_LastJobHistory = this.Columns["Prs_Fld_LastJobHistory"];
                this.columnPrs_Fld_LastJobHistory_Org = this.Columns["Prs_Fld_LastJobHistory_Org"];
                this.columnPrs_Fld_BirthYear = this.Columns["Prs_Fld_BirthYear"];
                this.columnPrs_Fld_BirthYear_Org = this.Columns["Prs_Fld_BirthYear_Org"];
                this.columnPrs_Fld_fk_StudyStatus = this.Columns["Prs_Fld_fk_StudyStatus"];
                this.columnPrs_Fld_fk_StudyStatus_Org = this.Columns["Prs_Fld_fk_StudyStatus_Org"];
                this.columnPrs_Fld_fk_EmployeeStatus = this.Columns["Prs_Fld_fk_EmployeeStatus"];
                this.columnPrs_Fld_fk_EmployeeStatus_Org = this.Columns["Prs_Fld_fk_EmployeeStatus_Org"];
                this.columnPrs_Fld_EmployeeDate = this.Columns["Prs_Fld_EmployeeDate"];
                this.columnPrs_Fld_EmployeeDate_Org = this.Columns["Prs_Fld_EmployeeDate_Org"];
                this.columnPrs_Fld_Address = this.Columns["Prs_Fld_Address"];
                this.columnPrs_Fld_TelNo = this.Columns["Prs_Fld_TelNo"];
                this.columnPrs_Fld_fk_OrgUnit = this.Columns["Prs_Fld_fk_OrgUnit"];
                this.columnPrs_Fld_fk_Region = this.Columns["Prs_Fld_fk_Region"];
                this.columnPrs_Fld_RegionDescribe = this.Columns["Prs_Fld_RegionDescribe"];
                this.columnPrs_Fld_fk_SubContractor = this.Columns["Prs_Fld_fk_SubContractor"];
                this.columnPrs_Fld_Contractor = this.Columns["Prs_Fld_Contractor"];
            }

            private void InitClass()
            {
                this.columnPrs_Fld_UniqueCode = new DataColumn("Prs_Fld_UniqueCode", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_UniqueCode);
                this.columnPrs_Fld_PersonelID = new DataColumn("Prs_Fld_PersonelID", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_PersonelID);
                this.columnPrs_Fld_PersonelID_Org = new DataColumn("Prs_Fld_PersonelID_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_PersonelID_Org);
                this.columnPrs_Fld_FirstName = new DataColumn("Prs_Fld_FirstName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_FirstName);
                this.columnPrs_Fld_FirstName_Org = new DataColumn("Prs_Fld_FirstName_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_FirstName_Org);
                this.columnPrs_Fld_LastName = new DataColumn("Prs_Fld_LastName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_LastName);
                this.columnPrs_Fld_LastName_Org = new DataColumn("Prs_Fld_LastName_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_LastName_Org);
                this.columnPrs_Fld_FullName = new DataColumn("Prs_Fld_FullName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_FullName);
                this.columnPrs_Fld_FatherName = new DataColumn("Prs_Fld_FatherName", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_FatherName);
                this.columnPrs_Fld_FatherName_Org = new DataColumn("Prs_Fld_FatherName_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_FatherName_Org);
                this.columnPrs_Fld_IDNo = new DataColumn("Prs_Fld_IDNo", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_IDNo);
                this.columnPrs_Fld_IDNo_Org = new DataColumn("Prs_Fld_IDNo_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_IDNo_Org);
                this.columnPrs_Fld_MaritalStatus = new DataColumn("Prs_Fld_MaritalStatus", typeof(byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_MaritalStatus);
                this.columnPrs_Fld_MaritalStatus_Org = new DataColumn("Prs_Fld_MaritalStatus_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_MaritalStatus_Org);
                this.columnPrs_Fld_fk_Job = new DataColumn("Prs_Fld_fk_Job", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_Job);
                this.columnPrs_Fld_JobDescribe = new DataColumn("Prs_Fld_JobDescribe", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_JobDescribe);
                this.columnPrs_Fld_fk_Job_Org = new DataColumn("Prs_Fld_fk_Job_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_Job_Org);
                this.columnPrs_Fld_fk_Job2 = new DataColumn("Prs_Fld_fk_Job2", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_Job2);
                this.columnPrs_Fld_fk_Job2_Org = new DataColumn("Prs_Fld_fk_Job2_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_Job2_Org);
                this.columnPrs_Fld_JobHistory = new DataColumn("Prs_Fld_JobHistory", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_JobHistory);
                this.columnPrs_Fld_JobHistory_Org = new DataColumn("Prs_Fld_JobHistory_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_JobHistory_Org);
                this.columnPrs_Fld_LastJobHistory = new DataColumn("Prs_Fld_LastJobHistory", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_LastJobHistory);
                this.columnPrs_Fld_LastJobHistory_Org = new DataColumn("Prs_Fld_LastJobHistory_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_LastJobHistory_Org);
                this.columnPrs_Fld_BirthYear = new DataColumn("Prs_Fld_BirthYear", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_BirthYear);
                this.columnPrs_Fld_BirthYear_Org = new DataColumn("Prs_Fld_BirthYear_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_BirthYear_Org);
                this.columnPrs_Fld_fk_StudyStatus = new DataColumn("Prs_Fld_fk_StudyStatus", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_StudyStatus);
                this.columnPrs_Fld_fk_StudyStatus_Org = new DataColumn("Prs_Fld_fk_StudyStatus_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_StudyStatus_Org);
                this.columnPrs_Fld_fk_EmployeeStatus = new DataColumn("Prs_Fld_fk_EmployeeStatus", typeof(System.Byte), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_EmployeeStatus);
                this.columnPrs_Fld_fk_EmployeeStatus_Org = new DataColumn("Prs_Fld_fk_EmployeeStatus_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_EmployeeStatus_Org);
                this.columnPrs_Fld_EmployeeDate = new DataColumn("Prs_Fld_EmployeeDate", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_EmployeeDate);
                this.columnPrs_Fld_EmployeeDate_Org = new DataColumn("Prs_Fld_EmployeeDate_Org", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_EmployeeDate_Org);
                this.columnPrs_Fld_Address = new DataColumn("Prs_Fld_Address", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_Address);
                this.columnPrs_Fld_TelNo = new DataColumn("Prs_Fld_TelNo", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_TelNo);
                this.columnPrs_Fld_fk_OrgUnit = new DataColumn("Prs_Fld_fk_OrgUnit", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_OrgUnit);
                this.columnPrs_Fld_fk_Region = new DataColumn("Prs_Fld_fk_Region", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_Region);
                this.columnPrs_Fld_RegionDescribe = new DataColumn("Prs_Fld_RegionDescribe", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_RegionDescribe);
                this.columnPrs_Fld_fk_SubContractor = new DataColumn("Prs_Fld_fk_SubContractor", typeof(int), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_fk_SubContractor);
                this.columnPrs_Fld_Contractor = new DataColumn("Prs_Fld_Contractor", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnPrs_Fld_Contractor);
                this.columnPrs_Fld_UniqueCode.AllowDBNull = false;
                this.columnPrs_Fld_FullName.ReadOnly = true;
            }

            public Prs_Sp_Sel_PersonelRow NewPrs_Sp_Sel_PersonelRow()
            {
                return ((Prs_Sp_Sel_PersonelRow)(this.NewRow()));
            }

            protected override DataRow NewRowFromBuilder(DataRowBuilder builder)
            {
                return new Prs_Sp_Sel_PersonelRow(builder);
            }

            protected override System.Type GetRowType()
            {
                return typeof(Prs_Sp_Sel_PersonelRow);
            }

            protected override void OnRowChanged(DataRowChangeEventArgs e)
            {
                base.OnRowChanged(e);
                if ((this.Prs_Sp_Sel_PersonelRowChanged != null))
                {
                    this.Prs_Sp_Sel_PersonelRowChanged(this, new Prs_Sp_Sel_PersonelRowChangeEvent(((Prs_Sp_Sel_PersonelRow)(e.Row)), e.Action));
                }
            }

            protected override void OnRowChanging(DataRowChangeEventArgs e)
            {
                base.OnRowChanging(e);
                if ((this.Prs_Sp_Sel_PersonelRowChanging != null))
                {
                    this.Prs_Sp_Sel_PersonelRowChanging(this, new Prs_Sp_Sel_PersonelRowChangeEvent(((Prs_Sp_Sel_PersonelRow)(e.Row)), e.Action));
                }
            }

            protected override void OnRowDeleted(DataRowChangeEventArgs e)
            {
                base.OnRowDeleted(e);
                if ((this.Prs_Sp_Sel_PersonelRowDeleted != null))
                {
                    this.Prs_Sp_Sel_PersonelRowDeleted(this, new Prs_Sp_Sel_PersonelRowChangeEvent(((Prs_Sp_Sel_PersonelRow)(e.Row)), e.Action));
                }
            }

            protected override void OnRowDeleting(DataRowChangeEventArgs e)
            {
                base.OnRowDeleting(e);
                if ((this.Prs_Sp_Sel_PersonelRowDeleting != null))
                {
                    this.Prs_Sp_Sel_PersonelRowDeleting(this, new Prs_Sp_Sel_PersonelRowChangeEvent(((Prs_Sp_Sel_PersonelRow)(e.Row)), e.Action));
                }
            }

            public void RemovePrs_Sp_Sel_PersonelRow(Prs_Sp_Sel_PersonelRow row)
            {
                this.Rows.Remove(row);
            }
        }

        [System.Diagnostics.DebuggerStepThrough()]
        public class Prs_Sp_Sel_PersonelRow : DataRow
        {

            private Prs_Sp_Sel_PersonelDataTable tablePrs_Sp_Sel_Personel;

            internal Prs_Sp_Sel_PersonelRow(DataRowBuilder rb)
                :
                    base(rb)
            {
                this.tablePrs_Sp_Sel_Personel = ((Prs_Sp_Sel_PersonelDataTable)(this.Table));
            }

            public int Prs_Fld_UniqueCode
            {
                get
                {
                    return ((int)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_UniqueCodeColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_UniqueCodeColumn] = value;
                }
            }

            public int Prs_Fld_PersonelID
            {
                get
                {
                    try
                    {
                        return ((int)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_PersonelIDColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_PersonelIDColumn] = value;
                }
            }

            public bool Prs_Fld_PersonelID_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_PersonelID_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_PersonelID_OrgColumn] = value;
                }
            }

            public string Prs_Fld_FirstName
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FirstNameColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FirstNameColumn] = value;
                }
            }

            public bool Prs_Fld_FirstName_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FirstName_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FirstName_OrgColumn] = value;
                }
            }

            public string Prs_Fld_LastName
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastNameColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastNameColumn] = value;
                }
            }

            public bool Prs_Fld_LastName_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastName_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastName_OrgColumn] = value;
                }
            }

            public string Prs_Fld_FullName
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FullNameColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FullNameColumn] = value;
                }
            }

            public string Prs_Fld_FatherName
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FatherNameColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FatherNameColumn] = value;
                }
            }

            public bool Prs_Fld_FatherName_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FatherName_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FatherName_OrgColumn] = value;
                }
            }

            public int Prs_Fld_IDNo
            {
                get
                {
                    try
                    {
                        return ((int)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_IDNoColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_IDNoColumn] = value;
                }
            }

            public bool Prs_Fld_IDNo_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_IDNo_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_IDNo_OrgColumn] = value;
                }
            }

            public byte Prs_Fld_MaritalStatus
            {
                get
                {
                    try
                    {
                        return ((byte)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_MaritalStatusColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_MaritalStatusColumn] = value;
                }
            }

            public bool Prs_Fld_MaritalStatus_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_MaritalStatus_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_MaritalStatus_OrgColumn] = value;
                }
            }

            public string Prs_Fld_fk_Job
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_JobColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_JobColumn] = value;
                }
            }

            public string Prs_Fld_JobDescribe
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobDescribeColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobDescribeColumn] = value;
                }
            }

            public bool Prs_Fld_fk_Job_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job_OrgColumn] = value;
                }
            }

            public string Prs_Fld_fk_Job2
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job2Column]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job2Column] = value;
                }
            }

            public bool Prs_Fld_fk_Job2_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job2_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job2_OrgColumn] = value;
                }
            }

            public short Prs_Fld_JobHistory
            {
                get
                {
                    try
                    {
                        return ((short)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobHistoryColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobHistoryColumn] = value;
                }
            }

            public bool Prs_Fld_JobHistory_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobHistory_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobHistory_OrgColumn] = value;
                }
            }

            public short Prs_Fld_LastJobHistory
            {
                get
                {
                    try
                    {
                        return ((short)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastJobHistoryColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastJobHistoryColumn] = value;
                }
            }

            public bool Prs_Fld_LastJobHistory_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastJobHistory_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastJobHistory_OrgColumn] = value;
                }
            }

            public short Prs_Fld_BirthYear
            {
                get
                {
                    try
                    {
                        return ((short)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_BirthYearColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_BirthYearColumn] = value;
                }
            }

            public bool Prs_Fld_BirthYear_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_BirthYear_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_BirthYear_OrgColumn] = value;
                }
            }

            public short Prs_Fld_fk_StudyStatus
            {
                get
                {
                    try
                    {
                        return ((short)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_StudyStatusColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_StudyStatusColumn] = value;
                }
            }

            public bool Prs_Fld_fk_StudyStatus_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_StudyStatus_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_StudyStatus_OrgColumn] = value;
                }
            }

            public System.Byte Prs_Fld_fk_EmployeeStatus
            {
                get
                {
                    try
                    {
                        return ((System.Byte)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_EmployeeStatusColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_EmployeeStatusColumn] = value;
                }
            }

            public bool Prs_Fld_fk_EmployeeStatus_Org
            {
                get
                {
                    return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_EmployeeStatus_OrgColumn]));
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_EmployeeStatus_OrgColumn] = value;
                }
            }

            public string Prs_Fld_EmployeeDate
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDateColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDateColumn] = value;
                }
            }

            public bool Prs_Fld_EmployeeDate_Org
            {
                get
                {
                    try
                    {
                        return ((bool)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDate_OrgColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDate_OrgColumn] = value;
                }
            }

            public string Prs_Fld_Address
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_AddressColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_AddressColumn] = value;
                }
            }

            public string Prs_Fld_TelNo
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_TelNoColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_TelNoColumn] = value;
                }
            }

            public int Prs_Fld_fk_OrgUnit
            {
                get
                {
                    try
                    {
                        return ((int)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_OrgUnitColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_OrgUnitColumn] = value;
                }
            }

            public int Prs_Fld_fk_Region
            {
                get
                {
                    try
                    {
                        return ((int)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_RegionColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_RegionColumn] = value;
                }
            }

            public string Prs_Fld_RegionDescribe
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_RegionDescribeColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_RegionDescribeColumn] = value;
                }
            }

            public int Prs_Fld_fk_SubContractor
            {
                get
                {
                    try
                    {
                        return ((int)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_SubContractorColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_SubContractorColumn] = value;
                }
            }

            public string Prs_Fld_Contractor
            {
                get
                {
                    try
                    {
                        return ((string)(this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_ContractorColumn]));
                    }
                    catch (InvalidCastException e)
                    {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set
                {
                    this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_ContractorColumn] = value;
                }
            }

            public bool IsPrs_Fld_PersonelIDNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_PersonelIDColumn);
            }

            public void SetPrs_Fld_PersonelIDNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_PersonelIDColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_FirstNameNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_FirstNameColumn);
            }

            public void SetPrs_Fld_FirstNameNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FirstNameColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_LastNameNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastNameColumn);
            }

            public void SetPrs_Fld_LastNameNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastNameColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_FullNameNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_FullNameColumn);
            }

            public void SetPrs_Fld_FullNameNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FullNameColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_FatherNameNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_FatherNameColumn);
            }

            public void SetPrs_Fld_FatherNameNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_FatherNameColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_IDNoNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_IDNoColumn);
            }

            public void SetPrs_Fld_IDNoNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_IDNoColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_MaritalStatusNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_MaritalStatusColumn);
            }

            public void SetPrs_Fld_MaritalStatusNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_MaritalStatusColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_JobNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_JobColumn);
            }

            public void SetPrs_Fld_fk_JobNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_JobColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_JobDescribeNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobDescribeColumn);
            }

            public void SetPrs_Fld_JobDescribeNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobDescribeColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_Job2Null()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job2Column);
            }

            public void SetPrs_Fld_fk_Job2Null()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_Job2Column] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_JobHistoryNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobHistoryColumn);
            }

            public void SetPrs_Fld_JobHistoryNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_JobHistoryColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_LastJobHistoryNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastJobHistoryColumn);
            }

            public void SetPrs_Fld_LastJobHistoryNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_LastJobHistoryColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_BirthYearNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_BirthYearColumn);
            }

            public void SetPrs_Fld_BirthYearNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_BirthYearColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_StudyStatusNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_StudyStatusColumn);
            }

            public void SetPrs_Fld_fk_StudyStatusNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_StudyStatusColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_EmployeeStatusNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_EmployeeStatusColumn);
            }

            public void SetPrs_Fld_fk_EmployeeStatusNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_EmployeeStatusColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_EmployeeDateNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDateColumn);
            }

            public void SetPrs_Fld_EmployeeDateNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDateColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_EmployeeDate_OrgNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDate_OrgColumn);
            }

            public void SetPrs_Fld_EmployeeDate_OrgNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_EmployeeDate_OrgColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_AddressNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_AddressColumn);
            }

            public void SetPrs_Fld_AddressNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_AddressColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_TelNoNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_TelNoColumn);
            }

            public void SetPrs_Fld_TelNoNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_TelNoColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_OrgUnitNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_OrgUnitColumn);
            }

            public void SetPrs_Fld_fk_OrgUnitNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_OrgUnitColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_RegionNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_RegionColumn);
            }

            public void SetPrs_Fld_fk_RegionNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_RegionColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_RegionDescribeNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_RegionDescribeColumn);
            }

            public void SetPrs_Fld_RegionDescribeNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_RegionDescribeColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_fk_SubContractorNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_SubContractorColumn);
            }

            public void SetPrs_Fld_fk_SubContractorNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_fk_SubContractorColumn] = System.Convert.DBNull;
            }

            public bool IsPrs_Fld_ContractorNull()
            {
                return this.IsNull(this.tablePrs_Sp_Sel_Personel.Prs_Fld_ContractorColumn);
            }

            public void SetPrs_Fld_ContractorNull()
            {
                this[this.tablePrs_Sp_Sel_Personel.Prs_Fld_ContractorColumn] = System.Convert.DBNull;
            }
        }

        [System.Diagnostics.DebuggerStepThrough()]
        public class Prs_Sp_Sel_PersonelRowChangeEvent : EventArgs
        {

            private Prs_Sp_Sel_PersonelRow eventRow;

            private DataRowAction eventAction;

            public Prs_Sp_Sel_PersonelRowChangeEvent(Prs_Sp_Sel_PersonelRow row, DataRowAction action)
            {
                this.eventRow = row;
                this.eventAction = action;
            }

            public Prs_Sp_Sel_PersonelRow Row
            {
                get
                {
                    return this.eventRow;
                }
            }

            public DataRowAction Action
            {
                get
                {
                    return this.eventAction;
                }
            }
        }
    }
}
