//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace shahriarco.Anbar.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QSumGhabzNMR
    {
        public int AnbarCode { get; set; }
        public Nullable<int> KalaCode { get; set; }
        public Nullable<double> MaxTedadGhabz { get; set; }
        public Nullable<double> MaxRialGhabz { get; set; }
        public string MadrakDate { get; set; }
    }
}
