SELECT 
sum(SL.SALESQTY),sum(SL.SALESPRICE),sum(SL.LINEAMOUNT)
/*
ST.SALESID,ST.SalesName,ST.CustAccount,ST.CustGroup,CAST(ST.CREATEDDATETIME AS DATE) CREATEDDATETIME, CAST(St.DeliveryDate AS DATE) DeliveryDate,
		 CASE WHEN ST.SALESSTATUS =1 THEN 'OPEN ORDER'
			  WHEN ST.SALESSTATUS =2 THEN 'DELIVERED'
			  WHEN ST.SALESSTATUS =3 THEN 'INVOICED'
			  WHEN ST.SALESSTATUS =4 THEN 'CANCELED'
		ELSE 'NONE' END AS SALESSTATUS
		 ,ST.INVENTLOCATIONID,SL.ITEMID,SL.SALESQTY,SL.SALESPRICE,SL.LINEAMOUNT
		,SL.linePercent, SL.lineDisc
	*/	
From SalesTable ST (NoLock)
INNER JOIN SalesLine SL (NoLock) ON ST.SalesID=SL.SalesId AND ST.PARTITION=SL.PARTITION AND ST.DATAAREAID=SL.DATAAREAID
WHERE
	ST.INVENTLOCATIONID NOT LIKE '%OKS%' 
	AND ST.CUSTGROUP!='Franchise'
	AND ST.DELIVERYDATE >= '2022-03-20 00:00:00.000'
	AND ST.DELIVERYDATE <  '2022-04-20 00:00:00.000'



	