//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace RWAS.Common
{
	using System;
	using System.Data;
	using System.Xml;
	using System.Runtime.Serialization;
    
    
	[Serializable()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Diagnostics.DebuggerStepThrough()]
	[System.ComponentModel.ToolboxItem(true)]
	public class dsOtherSystem : DataSet 
	{
        
		private Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable tableRws_Sp_Sel_ISEx_RepairRailWayVehicle;
        
		public dsOtherSystem() 
		{
			this.InitClass();
			System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			this.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
        
		protected dsOtherSystem(SerializationInfo info, StreamingContext context) 
		{
			string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
			if ((strSchema != null)) 
			{
				DataSet ds = new DataSet();
				ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
				if ((ds.Tables["Rws_Sp_Sel_ISEx_RepairRailWayVehicle"] != null)) 
				{
					this.Tables.Add(new Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable(ds.Tables["Rws_Sp_Sel_ISEx_RepairRailWayVehicle"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else 
			{
				this.InitClass();
			}
			this.GetSerializationData(info, context);
			System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			this.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}
        
		[System.ComponentModel.Browsable(false)]
		[System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
		public Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable Rws_Sp_Sel_ISEx_RepairRailWayVehicle 
		{
			get 
			{
				return this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle;
			}
		}
        
		public override DataSet Clone() 
		{
			dsOtherSystem cln = ((dsOtherSystem)(base.Clone()));
			cln.InitVars();
			return cln;
		}
        
		protected override bool ShouldSerializeTables() 
		{
			return false;
		}
        
		protected override bool ShouldSerializeRelations() 
		{
			return false;
		}
        
		protected override void ReadXmlSerializable(XmlReader reader) 
		{
			this.Reset();
			DataSet ds = new DataSet();
			ds.ReadXml(reader);
			if ((ds.Tables["Rws_Sp_Sel_ISEx_RepairRailWayVehicle"] != null)) 
			{
				this.Tables.Add(new Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable(ds.Tables["Rws_Sp_Sel_ISEx_RepairRailWayVehicle"]));
			}
			this.DataSetName = ds.DataSetName;
			this.Prefix = ds.Prefix;
			this.Namespace = ds.Namespace;
			this.Locale = ds.Locale;
			this.CaseSensitive = ds.CaseSensitive;
			this.EnforceConstraints = ds.EnforceConstraints;
			this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			this.InitVars();
		}
        
		protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() 
		{
			System.IO.MemoryStream stream = new System.IO.MemoryStream();
			this.WriteXmlSchema(new XmlTextWriter(stream, null));
			stream.Position = 0;
			return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
		}
        
		internal void InitVars() 
		{
			this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle = ((Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable)(this.Tables["Rws_Sp_Sel_ISEx_RepairRailWayVehicle"]));
			if ((this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle != null)) 
			{
				this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.InitVars();
			}
		}
        
		private void InitClass() 
		{
			this.DataSetName = "dsOtherSystem";
			this.Prefix = "";
			this.Namespace = "http://tempuri.org/dsOtherSystem.xsd";
			this.Locale = new System.Globalization.CultureInfo("en-US");
			this.CaseSensitive = false;
			this.EnforceConstraints = true;
			this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle = new Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable();
			this.Tables.Add(this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle);
		}
        
		private bool ShouldSerializeRws_Sp_Sel_ISEx_RepairRailWayVehicle() 
		{
			return false;
		}
        
		private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) 
		{
			if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) 
			{
				this.InitVars();
			}
		}
        
		public delegate void Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEventHandler(object sender, Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent e);
        
		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable : DataTable, System.Collections.IEnumerable 
		{
            
			private DataColumn columnRws_Fld_fk_RailWayVehicle;
            
			private DataColumn columnRws_Fld_Row;
            
			private DataColumn columnRws_Fld_BasicRepairDate;
            
			private DataColumn columnRws_Fld_18MonthlyRepairDate;
            
			private DataColumn columnRws_fld_fk_RepairKind;
            
			internal Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable() : 
				base("Rws_Sp_Sel_ISEx_RepairRailWayVehicle") 
			{
				this.InitClass();
			}
            
			internal Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
				this.DisplayExpression = table.DisplayExpression;
			}
            
			[System.ComponentModel.Browsable(false)]
			public int Count 
			{
				get 
				{
					return this.Rows.Count;
				}
			}
            
			internal DataColumn Rws_Fld_fk_RailWayVehicleColumn 
			{
				get 
				{
					return this.columnRws_Fld_fk_RailWayVehicle;
				}
			}
            
			internal DataColumn Rws_Fld_RowColumn 
			{
				get 
				{
					return this.columnRws_Fld_Row;
				}
			}
            
			internal DataColumn Rws_Fld_BasicRepairDateColumn 
			{
				get 
				{
					return this.columnRws_Fld_BasicRepairDate;
				}
			}
            
			internal DataColumn Rws_Fld_18MonthlyRepairDateColumn 
			{
				get 
				{
					return this.columnRws_Fld_18MonthlyRepairDate;
				}
			}
            
			internal DataColumn Rws_fld_fk_RepairKindColumn 
			{
				get 
				{
					return this.columnRws_fld_fk_RepairKind;
				}
			}
            
			public Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow this[int index] 
			{
				get 
				{
					return ((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(this.Rows[index]));
				}
			}
            
			public event Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEventHandler Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChanged;
            
			public event Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEventHandler Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChanging;
            
			public event Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEventHandler Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowDeleted;
            
			public event Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEventHandler Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowDeleting;
            
			public void AddRws_Sp_Sel_ISEx_RepairRailWayVehicleRow(Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow row) 
			{
				this.Rows.Add(row);
			}
            
			public Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow AddRws_Sp_Sel_ISEx_RepairRailWayVehicleRow(int Rws_Fld_fk_RailWayVehicle, int Rws_Fld_Row, string Rws_Fld_BasicRepairDate, string Rws_Fld_18MonthlyRepairDate, System.Byte Rws_fld_fk_RepairKind) 
			{
				Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow rowRws_Sp_Sel_ISEx_RepairRailWayVehicleRow = ((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(this.NewRow()));
				rowRws_Sp_Sel_ISEx_RepairRailWayVehicleRow.ItemArray = new object[] {
																						Rws_Fld_fk_RailWayVehicle,
																						Rws_Fld_Row,
																						Rws_Fld_BasicRepairDate,
																						Rws_Fld_18MonthlyRepairDate,
																						Rws_fld_fk_RepairKind};
				this.Rows.Add(rowRws_Sp_Sel_ISEx_RepairRailWayVehicleRow);
				return rowRws_Sp_Sel_ISEx_RepairRailWayVehicleRow;
			}
            
			public System.Collections.IEnumerator GetEnumerator() 
			{
				return this.Rows.GetEnumerator();
			}
            
			public override DataTable Clone() 
			{
				Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable cln = ((Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
            
			protected override DataTable CreateInstance() 
			{
				return new Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable();
			}
            
			internal void InitVars() 
			{
				this.columnRws_Fld_fk_RailWayVehicle = this.Columns["Rws_Fld_fk_RailWayVehicle"];
				this.columnRws_Fld_Row = this.Columns["Rws_Fld_Row"];
				this.columnRws_Fld_BasicRepairDate = this.Columns["Rws_Fld_BasicRepairDate"];
				this.columnRws_Fld_18MonthlyRepairDate = this.Columns["Rws_Fld_18MonthlyRepairDate"];
				this.columnRws_fld_fk_RepairKind = this.Columns["Rws_fld_fk_RepairKind"];
			}
            
			private void InitClass() 
			{
				this.columnRws_Fld_fk_RailWayVehicle = new DataColumn("Rws_Fld_fk_RailWayVehicle", typeof(int), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_fk_RailWayVehicle);
				this.columnRws_Fld_Row = new DataColumn("Rws_Fld_Row", typeof(int), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_Row);
				this.columnRws_Fld_BasicRepairDate = new DataColumn("Rws_Fld_BasicRepairDate", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_BasicRepairDate);
				this.columnRws_Fld_18MonthlyRepairDate = new DataColumn("Rws_Fld_18MonthlyRepairDate", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_18MonthlyRepairDate);
				this.columnRws_fld_fk_RepairKind = new DataColumn("Rws_fld_fk_RepairKind", typeof(System.Byte), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_fld_fk_RepairKind);
				this.columnRws_Fld_fk_RailWayVehicle.AllowDBNull = false;
				this.columnRws_Fld_Row.AllowDBNull = false;
			}
            
			public Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow NewRws_Sp_Sel_ISEx_RepairRailWayVehicleRow() 
			{
				return ((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(this.NewRow()));
			}
            
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow(builder);
			}
            
			protected override System.Type GetRowType() 
			{
				return typeof(Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow);
			}
            
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChanged != null)) 
				{
					this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChanged(this, new Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent(((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(e.Row)), e.Action));
				}
			}
            
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChanging != null)) 
				{
					this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChanging(this, new Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent(((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(e.Row)), e.Action));
				}
			}
            
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowDeleted != null)) 
				{
					this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowDeleted(this, new Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent(((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(e.Row)), e.Action));
				}
			}
            
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowDeleting != null)) 
				{
					this.Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowDeleting(this, new Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent(((Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow)(e.Row)), e.Action));
				}
			}
            
			public void RemoveRws_Sp_Sel_ISEx_RepairRailWayVehicleRow(Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow row) 
			{
				this.Rows.Remove(row);
			}
		}
        
		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow : DataRow 
		{
            
			private Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable tableRws_Sp_Sel_ISEx_RepairRailWayVehicle;
            
			internal Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow(DataRowBuilder rb) : 
				base(rb) 
			{
				this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle = ((Rws_Sp_Sel_ISEx_RepairRailWayVehicleDataTable)(this.Table));
			}
            
			public int Rws_Fld_fk_RailWayVehicle 
			{
				get 
				{
					return ((int)(this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_fk_RailWayVehicleColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_fk_RailWayVehicleColumn] = value;
				}
			}
            
			public int Rws_Fld_Row 
			{
				get 
				{
					return ((int)(this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_RowColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_RowColumn] = value;
				}
			}
            
			public string Rws_Fld_BasicRepairDate 
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_BasicRepairDateColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_BasicRepairDateColumn] = value;
				}
			}
            
			public string Rws_Fld_18MonthlyRepairDate 
			{
				get 
				{
					try 
					{
						return ((string)(this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_18MonthlyRepairDateColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_18MonthlyRepairDateColumn] = value;
				}
			}
            
			public System.Byte Rws_fld_fk_RepairKind 
			{
				get 
				{
					try 
					{
						return ((System.Byte)(this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_fld_fk_RepairKindColumn]));
					}
					catch (InvalidCastException e) 
					{
						throw new StrongTypingException("Cannot get value because it is DBNull.", e);
					}
				}
				set 
				{
					this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_fld_fk_RepairKindColumn] = value;
				}
			}
            
			public bool IsRws_Fld_BasicRepairDateNull() 
			{
				return this.IsNull(this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_BasicRepairDateColumn);
			}
            
			public void SetRws_Fld_BasicRepairDateNull() 
			{
				this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_BasicRepairDateColumn] = System.Convert.DBNull;
			}
            
			public bool IsRws_Fld_18MonthlyRepairDateNull() 
			{
				return this.IsNull(this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_18MonthlyRepairDateColumn);
			}
            
			public void SetRws_Fld_18MonthlyRepairDateNull() 
			{
				this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_Fld_18MonthlyRepairDateColumn] = System.Convert.DBNull;
			}
            
			public bool IsRws_fld_fk_RepairKindNull() 
			{
				return this.IsNull(this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_fld_fk_RepairKindColumn);
			}
            
			public void SetRws_fld_fk_RepairKindNull() 
			{
				this[this.tableRws_Sp_Sel_ISEx_RepairRailWayVehicle.Rws_fld_fk_RepairKindColumn] = System.Convert.DBNull;
			}
		}
        
		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent : EventArgs 
		{
            
			private Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow eventRow;
            
			private DataRowAction eventAction;
            
			public Rws_Sp_Sel_ISEx_RepairRailWayVehicleRowChangeEvent(Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow row, DataRowAction action) 
			{
				this.eventRow = row;
				this.eventAction = action;
			}
            
			public Rws_Sp_Sel_ISEx_RepairRailWayVehicleRow Row 
			{
				get 
				{
					return this.eventRow;
				}
			}
            
			public DataRowAction Action 
			{
				get 
				{
					return this.eventAction;
				}
			}
		}
	}
}
