VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "Amanat"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public IntraProvincePrice As Long

Public InterProvincePrice As Long

Public ExtraProvinceTejariPriceRestant As Long
Public ExtraProvinceTejariPrice As Long

Public ToIslandsExtraPrice As Long

Public FromFreeZonePrice As Long

Public FromKishAndGheshmPrice As Long

Public MassAmanat21Percentage As Single

Public MassAmanat10U20Percentage As Single

Public OutOfSizePercentage As Single
        
'' OutOfStandardPackage
Public OutOfStandardPackagePercentage As Single
'' OutOfStandardPackage

Public MayeAndBreakPercentage As Single

Public BankAndMoneyExtraPrice As Long

