VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "InternationalSpecialServices"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public MarsoleRegistrationPrice As Long  'Excluding Amanat
Public SpecialBagRegistrationPrice As Long
Public GettingFromCustumesWithCN22 As Long
Public DestinationDestpatchPrice As Long
Public ExpressPrice As Long
Public ReturnChangePrice As Long
Public DispatchSmallPackagesOrAmanatPrice As Long

''<> NewsAndM
'Public NewsRegistrationPrice As Long
'Public NewsAndMGettingFromCustumesWithCN22 As Long
'Public NewsAndMExpressPrice As Long
'Public NewsAndMReturnChangePrice As Long
''</> NewsAndM

