VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
  Persistable = 0  'NotPersistable
  DataBindingBehavior = 0  'vbNone
  DataSourceBehavior  = 0  'vbNone
  MTSTransactionMode  = 0  'NotAnMTSObject
END
Attribute VB_Name = "LocalSpecialServices"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = True
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Attribute VB_Ext_KEY = "SavedWithClassBuilder6" ,"Yes"
Attribute VB_Ext_KEY = "Top_Level" ,"Yes"
Option Explicit

Public MarsoleRegistrationPrice As Long  'Including Amanat
Public SpecialBagRegistrationPrice As Long
Public ExpressU2Price As Long
Public ExtraExpressPrice As Long
Public ReturnChangePrice As Long
Public EMSReturnReceiptPrice As Long
Public EMSReturnReceiptPriceKharej As Long
Public OutOfTimeAcceptanceDayPrice As Long
Public OutOfTimeAcceptanceNightPrice As Long

''<>NewsAndM
'Public NewsRegistrationPrice As Long
'Public NewsAndMExpressU2Price As Long
'Public NewsAndMExtraExpressPrice As Long
'Public NewsAndMReturnChangePrice As Long
''</>NewsAndM

