//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace RWAS.Common
{
    using System;
    using System.Data;
    using System.Xml;
    using System.Runtime.Serialization;
    
    
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Diagnostics.DebuggerStepThrough()]
    [System.ComponentModel.ToolboxItem(true)]
    public class clsDSRegion : DataSet {
        
        private Rws_Sp_Sel_All_Region2DataTable tableRws_Sp_Sel_All_Region2;
        
		public const string Rws_Fld_Code = "Rws_Fld_Code";
		public const string Rws_Fld_Describe = "Rws_Fld_Describe";
		public const string Rws_Fld_IsUsed = "Rws_Fld_IsUsed";
		
		public clsDSRegion() 
		{
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        protected clsDSRegion(SerializationInfo info, StreamingContext context) {
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((strSchema != null)) {
                DataSet ds = new DataSet();
                ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Rws_Sp_Sel_All_Region2"] != null)) {
                    this.Tables.Add(new Rws_Sp_Sel_All_Region2DataTable(ds.Tables["Rws_Sp_Sel_All_Region2"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.InitClass();
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            this.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Rws_Sp_Sel_All_Region2DataTable Rws_Sp_Sel_All_Region2 {
            get {
                return this.tableRws_Sp_Sel_All_Region2;
            }
        }
        
        public override DataSet Clone() {
            clsDSRegion cln = ((clsDSRegion)(base.Clone()));
            cln.InitVars();
            return cln;
        }
        
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        protected override void ReadXmlSerializable(XmlReader reader) {
            this.Reset();
            DataSet ds = new DataSet();
            ds.ReadXml(reader);
            if ((ds.Tables["Rws_Sp_Sel_All_Region2"] != null)) {
                this.Tables.Add(new Rws_Sp_Sel_All_Region2DataTable(ds.Tables["Rws_Sp_Sel_All_Region2"]));
            }
            this.DataSetName = ds.DataSetName;
            this.Prefix = ds.Prefix;
            this.Namespace = ds.Namespace;
            this.Locale = ds.Locale;
            this.CaseSensitive = ds.CaseSensitive;
            this.EnforceConstraints = ds.EnforceConstraints;
            this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
            this.InitVars();
        }
        
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
        }
        
        internal void InitVars() {
            this.tableRws_Sp_Sel_All_Region2 = ((Rws_Sp_Sel_All_Region2DataTable)(this.Tables["Rws_Sp_Sel_All_Region2"]));
            if ((this.tableRws_Sp_Sel_All_Region2 != null)) {
                this.tableRws_Sp_Sel_All_Region2.InitVars();
            }
        }
        
        private void InitClass() {
            this.DataSetName = "clsDSRegion";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/clsDSRegion.xsd";
            this.Locale = new System.Globalization.CultureInfo("en-US");
            this.CaseSensitive = false;
            this.EnforceConstraints = true;
            this.tableRws_Sp_Sel_All_Region2 = new Rws_Sp_Sel_All_Region2DataTable();
            this.Tables.Add(this.tableRws_Sp_Sel_All_Region2);
        }
        
        private bool ShouldSerializeRws_Sp_Sel_All_Region2() {
            return false;
        }
        
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        public delegate void Rws_Sp_Sel_All_Region2RowChangeEventHandler(object sender, Rws_Sp_Sel_All_Region2RowChangeEvent e);
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Rws_Sp_Sel_All_Region2DataTable : DataTable, System.Collections.IEnumerable {
            
            private DataColumn columnRws_Fld_Code;
            
            private DataColumn columnRws_Fld_Describe;
            
            private DataColumn columnRws_Fld_IsUsed;
            
            internal Rws_Sp_Sel_All_Region2DataTable() : 
                    base("Rws_Sp_Sel_All_Region2") {
                this.InitClass();
            }
            
            internal Rws_Sp_Sel_All_Region2DataTable(DataTable table) : 
                    base(table.TableName) {
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
                this.DisplayExpression = table.DisplayExpression;
            }
            
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            internal DataColumn Rws_Fld_CodeColumn {
                get {
                    return this.columnRws_Fld_Code;
                }
            }
            
            internal DataColumn Rws_Fld_DescribeColumn {
                get {
                    return this.columnRws_Fld_Describe;
                }
            }
            
            
            internal DataColumn Rws_Fld_IsUsedColumn {
                get {
                    return this.columnRws_Fld_IsUsed;
                }
            }
            
            public Rws_Sp_Sel_All_Region2Row this[int index] {
                get {
                    return ((Rws_Sp_Sel_All_Region2Row)(this.Rows[index]));
                }
            }
            
            public event Rws_Sp_Sel_All_Region2RowChangeEventHandler Rws_Sp_Sel_All_Region2RowChanged;
            
            public event Rws_Sp_Sel_All_Region2RowChangeEventHandler Rws_Sp_Sel_All_Region2RowChanging;
            
            public event Rws_Sp_Sel_All_Region2RowChangeEventHandler Rws_Sp_Sel_All_Region2RowDeleted;
            
            public event Rws_Sp_Sel_All_Region2RowChangeEventHandler Rws_Sp_Sel_All_Region2RowDeleting;
            
            public void AddRws_Sp_Sel_All_Region2Row(Rws_Sp_Sel_All_Region2Row row) {
                this.Rows.Add(row);
            }
            
            public Rws_Sp_Sel_All_Region2Row AddRws_Sp_Sel_All_Region2Row(string Rws_Fld_Describe, bool Rws_Fld_IsUsed) {
                Rws_Sp_Sel_All_Region2Row rowRws_Sp_Sel_All_Region2Row = ((Rws_Sp_Sel_All_Region2Row)(this.NewRow()));
                rowRws_Sp_Sel_All_Region2Row.ItemArray = new object[] {
                        null,
                        Rws_Fld_Describe,
                        Rws_Fld_IsUsed};
                this.Rows.Add(rowRws_Sp_Sel_All_Region2Row);
                return rowRws_Sp_Sel_All_Region2Row;
            }
            
            public Rws_Sp_Sel_All_Region2Row FindByRws_Fld_Code(short Rws_Fld_Code) {
                return ((Rws_Sp_Sel_All_Region2Row)(this.Rows.Find(new object[] {
                            Rws_Fld_Code})));
            }
            
            public System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            public override DataTable Clone() {
                Rws_Sp_Sel_All_Region2DataTable cln = ((Rws_Sp_Sel_All_Region2DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            protected override DataTable CreateInstance() {
                return new Rws_Sp_Sel_All_Region2DataTable();
            }
            
            internal void InitVars() {
                this.columnRws_Fld_Code = this.Columns["Rws_Fld_Code"];
                this.columnRws_Fld_Describe = this.Columns["Rws_Fld_Describe"];
                this.columnRws_Fld_IsUsed = this.Columns["Rws_Fld_IsUsed"];
            }
            
            private void InitClass() {
                this.columnRws_Fld_Code = new DataColumn("Rws_Fld_Code", typeof(short), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRws_Fld_Code);
                this.columnRws_Fld_Describe = new DataColumn("Rws_Fld_Describe", typeof(string), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRws_Fld_Describe);
                this.columnRws_Fld_IsUsed = new DataColumn("Rws_Fld_IsUsed", typeof(bool), null, System.Data.MappingType.Element);
                this.Columns.Add(this.columnRws_Fld_IsUsed);
                this.Constraints.Add(new UniqueConstraint("clsDSRegionKey1", new DataColumn[] {
                                this.columnRws_Fld_Code}, true));
                this.columnRws_Fld_Code.AutoIncrement = true;
                this.columnRws_Fld_Code.AllowDBNull = false;
                this.columnRws_Fld_Code.ReadOnly = true;
                this.columnRws_Fld_Code.Unique = true;
                this.columnRws_Fld_Describe.AllowDBNull = false;
                this.columnRws_Fld_IsUsed.ReadOnly = true;
            }
            
            public Rws_Sp_Sel_All_Region2Row NewRws_Sp_Sel_All_Region2Row() {
                return ((Rws_Sp_Sel_All_Region2Row)(this.NewRow()));
            }
            
            protected override DataRow NewRowFromBuilder(DataRowBuilder builder) {
                return new Rws_Sp_Sel_All_Region2Row(builder);
            }
            
            protected override System.Type GetRowType() {
                return typeof(Rws_Sp_Sel_All_Region2Row);
            }
            
            protected override void OnRowChanged(DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Rws_Sp_Sel_All_Region2RowChanged != null)) {
                    this.Rws_Sp_Sel_All_Region2RowChanged(this, new Rws_Sp_Sel_All_Region2RowChangeEvent(((Rws_Sp_Sel_All_Region2Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowChanging(DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Rws_Sp_Sel_All_Region2RowChanging != null)) {
                    this.Rws_Sp_Sel_All_Region2RowChanging(this, new Rws_Sp_Sel_All_Region2RowChangeEvent(((Rws_Sp_Sel_All_Region2Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleted(DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Rws_Sp_Sel_All_Region2RowDeleted != null)) {
                    this.Rws_Sp_Sel_All_Region2RowDeleted(this, new Rws_Sp_Sel_All_Region2RowChangeEvent(((Rws_Sp_Sel_All_Region2Row)(e.Row)), e.Action));
                }
            }
            
            protected override void OnRowDeleting(DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Rws_Sp_Sel_All_Region2RowDeleting != null)) {
                    this.Rws_Sp_Sel_All_Region2RowDeleting(this, new Rws_Sp_Sel_All_Region2RowChangeEvent(((Rws_Sp_Sel_All_Region2Row)(e.Row)), e.Action));
                }
            }
            
            public void RemoveRws_Sp_Sel_All_Region2Row(Rws_Sp_Sel_All_Region2Row row) {
                this.Rows.Remove(row);
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Rws_Sp_Sel_All_Region2Row : DataRow {
            
            private Rws_Sp_Sel_All_Region2DataTable tableRws_Sp_Sel_All_Region2;
            
            internal Rws_Sp_Sel_All_Region2Row(DataRowBuilder rb) : 
                    base(rb) {
                this.tableRws_Sp_Sel_All_Region2 = ((Rws_Sp_Sel_All_Region2DataTable)(this.Table));
            }
            
            public short Rws_Fld_Code {
                get {
                    return ((short)(this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_CodeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_CodeColumn] = value;
                }
            }
            
            public string Rws_Fld_Describe {
                get {
                    return ((string)(this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_DescribeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_DescribeColumn] = value;
                }
            }
            
            public bool Rws_Fld_IsUsed {
                get {
                    try {
                        return ((bool)(this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_IsUsedColumn]));
                    }
                    catch (InvalidCastException e) {
                        throw new StrongTypingException("Cannot get value because it is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_IsUsedColumn] = value;
                }
            }
            
            public bool IsRws_Fld_IsUsedNull() {
                return this.IsNull(this.tableRws_Sp_Sel_All_Region2.Rws_Fld_IsUsedColumn);
            }
            
            public void SetRws_Fld_IsUsedNull() {
                this[this.tableRws_Sp_Sel_All_Region2.Rws_Fld_IsUsedColumn] = System.Convert.DBNull;
            }
        }
        
        [System.Diagnostics.DebuggerStepThrough()]
        public class Rws_Sp_Sel_All_Region2RowChangeEvent : EventArgs {
            
            private Rws_Sp_Sel_All_Region2Row eventRow;
            
            private DataRowAction eventAction;
            
            public Rws_Sp_Sel_All_Region2RowChangeEvent(Rws_Sp_Sel_All_Region2Row row, DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            public Rws_Sp_Sel_All_Region2Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            public DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
