//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace RWAS.Common
{
	using System;
	using System.Data;
	using System.Xml;
	using System.Runtime.Serialization;


	[Serializable()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Diagnostics.DebuggerStepThrough()]
	[System.ComponentModel.ToolboxItem(true)]
	public class clsDSStation : DataSet 
	{

		private Rws_Sp_Sel_All_NewStationDataTable tableRws_Sp_Sel_All_NewStation;

		public const string Rws_Fld_fk_Region = "Rws_Fld_fk_Region";
		public const string Rws_Fld_RegionDescribe = "Rws_Fld_RegionDescribe";
		public const string Rws_Fld_Code = "Rws_Fld_Code";
		public const string Rws_Fld_Describe = "Rws_Fld_Describe";
		public const string Rws_Fld_ufk_StationKind = "Rws_Fld_ufk_StationKind";
		public const string Rws_Fld_StationKindDescribe = "Rws_Fld_StationKindDescribe";
		public const string Rws_Fld_pk_Station = "Rws_Fld_pk_Station";
		public const string Rws_Fld_IsConfirm = "Rws_Fld_IsConfirm";
		public const string Rws_Fld_IsConfirmVir = "Rws_Fld_IsConfirmVir";
		public const string Rws_Fld_Flag = "Rws_Fld_Flag";

		private Rws_Sp_Sel_All_RegionDataTable tableRws_Sp_Sel_All_Region;

		private DataRelation relationRws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation;

		public clsDSStation() 
		{
			this.InitClass();
			System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			this.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}

		protected clsDSStation(SerializationInfo info, StreamingContext context) 
		{
			string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
			if ((strSchema != null)) 
			{
				DataSet ds = new DataSet();
				ds.ReadXmlSchema(new XmlTextReader(new System.IO.StringReader(strSchema)));
				if ((ds.Tables["Rws_Sp_Sel_All_NewStation"] != null)) 
				{
					this.Tables.Add(new Rws_Sp_Sel_All_NewStationDataTable(ds.Tables["Rws_Sp_Sel_All_NewStation"]));
				}
				if ((ds.Tables["Rws_Sp_Sel_All_Region"] != null)) 
				{
					this.Tables.Add(new Rws_Sp_Sel_All_RegionDataTable(ds.Tables["Rws_Sp_Sel_All_Region"]));
				}
				this.DataSetName = ds.DataSetName;
				this.Prefix = ds.Prefix;
				this.Namespace = ds.Namespace;
				this.Locale = ds.Locale;
				this.CaseSensitive = ds.CaseSensitive;
				this.EnforceConstraints = ds.EnforceConstraints;
				this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
				this.InitVars();
			}
			else 
			{
				this.InitClass();
			}
			this.GetSerializationData(info, context);
			System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
			this.Tables.CollectionChanged += schemaChangedHandler;
			this.Relations.CollectionChanged += schemaChangedHandler;
		}

		[System.ComponentModel.Browsable(false)]
		[System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
		public Rws_Sp_Sel_All_NewStationDataTable Rws_Sp_Sel_All_NewStation 
		{
			get 
			{
				return this.tableRws_Sp_Sel_All_NewStation;
			}
		}

		[System.ComponentModel.Browsable(false)]
		[System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Content)]
		public Rws_Sp_Sel_All_RegionDataTable Rws_Sp_Sel_All_Region 
		{
			get 
			{
				return this.tableRws_Sp_Sel_All_Region;
			}
		}

		public override DataSet Clone() 
		{
			clsDSStation cln = ((clsDSStation)(base.Clone()));
			cln.InitVars();
			return cln;
		}

		protected override bool ShouldSerializeTables() 
		{
			return false;
		}

		protected override bool ShouldSerializeRelations() 
		{
			return false;
		}

		protected override void ReadXmlSerializable(XmlReader reader) 
		{
			this.Reset();
			DataSet ds = new DataSet();
			ds.ReadXml(reader);
			if ((ds.Tables["Rws_Sp_Sel_All_NewStation"] != null)) 
			{
				this.Tables.Add(new Rws_Sp_Sel_All_NewStationDataTable(ds.Tables["Rws_Sp_Sel_All_NewStation"]));
			}
			if ((ds.Tables["Rws_Sp_Sel_All_Region"] != null)) 
			{
				this.Tables.Add(new Rws_Sp_Sel_All_RegionDataTable(ds.Tables["Rws_Sp_Sel_All_Region"]));
			}
			this.DataSetName = ds.DataSetName;
			this.Prefix = ds.Prefix;
			this.Namespace = ds.Namespace;
			this.Locale = ds.Locale;
			this.CaseSensitive = ds.CaseSensitive;
			this.EnforceConstraints = ds.EnforceConstraints;
			this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
			this.InitVars();
		}

		protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() 
		{
			System.IO.MemoryStream stream = new System.IO.MemoryStream();
			this.WriteXmlSchema(new XmlTextWriter(stream, null));
			stream.Position = 0;
			return System.Xml.Schema.XmlSchema.Read(new XmlTextReader(stream), null);
		}

		internal void InitVars() 
		{
			this.tableRws_Sp_Sel_All_NewStation = ((Rws_Sp_Sel_All_NewStationDataTable)(this.Tables["Rws_Sp_Sel_All_NewStation"]));
			if ((this.tableRws_Sp_Sel_All_NewStation != null)) 
			{
				this.tableRws_Sp_Sel_All_NewStation.InitVars();
			}
			this.tableRws_Sp_Sel_All_Region = ((Rws_Sp_Sel_All_RegionDataTable)(this.Tables["Rws_Sp_Sel_All_Region"]));
			if ((this.tableRws_Sp_Sel_All_Region != null)) 
			{
				this.tableRws_Sp_Sel_All_Region.InitVars();
			}
			this.relationRws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation = this.Relations["Rws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation"];
		}

		private void InitClass() 
		{
			this.DataSetName = "clsDSStation";
			this.Prefix = "";
			this.Namespace = "http://tempuri.org/clsDSStation.xsd";
			this.Locale = new System.Globalization.CultureInfo("en-US");
			this.CaseSensitive = false;
			this.EnforceConstraints = true;
			this.tableRws_Sp_Sel_All_NewStation = new Rws_Sp_Sel_All_NewStationDataTable();
			this.Tables.Add(this.tableRws_Sp_Sel_All_NewStation);
			this.tableRws_Sp_Sel_All_Region = new Rws_Sp_Sel_All_RegionDataTable();
			this.Tables.Add(this.tableRws_Sp_Sel_All_Region);
			ForeignKeyConstraint fkc;
			fkc = new ForeignKeyConstraint("Rws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation", new DataColumn[] {
																													this.tableRws_Sp_Sel_All_Region.Rws_Fld_CodeColumn}, new DataColumn[] {
																																															this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_fk_RegionColumn});
			this.tableRws_Sp_Sel_All_NewStation.Constraints.Add(fkc);
			fkc.AcceptRejectRule = System.Data.AcceptRejectRule.None;
			fkc.DeleteRule = System.Data.Rule.Cascade;
			fkc.UpdateRule = System.Data.Rule.Cascade;
			this.relationRws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation = new DataRelation("Rws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation", new DataColumn[] {
																																									this.tableRws_Sp_Sel_All_Region.Rws_Fld_CodeColumn}, new DataColumn[] {
																																																											this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_fk_RegionColumn}, false);
			this.Relations.Add(this.relationRws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation);
		}

		private bool ShouldSerializeRws_Sp_Sel_All_NewStation() 
		{
			return false;
		}

		private bool ShouldSerializeRws_Sp_Sel_All_Region() 
		{
			return false;
		}

		private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) 
		{
			if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) 
			{
				this.InitVars();
			}
		}

		public delegate void Rws_Sp_Sel_All_NewStationRowChangeEventHandler(object sender, Rws_Sp_Sel_All_NewStationRowChangeEvent e);

		public delegate void Rws_Sp_Sel_All_RegionRowChangeEventHandler(object sender, Rws_Sp_Sel_All_RegionRowChangeEvent e);

		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_All_NewStationDataTable : DataTable, System.Collections.IEnumerable 
		{
    
			private DataColumn columnRws_Fld_fk_Region;
    
			private DataColumn columnRws_Fld_RegionDescribe;
    
			private DataColumn columnRws_Fld_Code;
    
			private DataColumn columnRws_Fld_Describe;
    
			private DataColumn columnRws_Fld_ufk_StationKind;
    
			private DataColumn columnRws_Fld_StationKindDescribe;
    
			private DataColumn columnRws_Fld_pk_Station;
    
			private DataColumn columnRws_Fld_IsConfirm;
    
			private DataColumn columnRws_Fld_IsConfirmVir;
    
			private DataColumn columnRws_Fld_Flag;
    
			internal Rws_Sp_Sel_All_NewStationDataTable() : 
				base("Rws_Sp_Sel_All_NewStation") 
			{
				this.InitClass();
			}
    
			internal Rws_Sp_Sel_All_NewStationDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
				this.DisplayExpression = table.DisplayExpression;
			}
    
			[System.ComponentModel.Browsable(false)]
			public int Count 
			{
				get 
				{
					return this.Rows.Count;
				}
			}
    
			internal DataColumn Rws_Fld_fk_RegionColumn 
			{
				get 
				{
					return this.columnRws_Fld_fk_Region;
				}
			}
    
			internal DataColumn Rws_Fld_RegionDescribeColumn 
			{
				get 
				{
					return this.columnRws_Fld_RegionDescribe;
				}
			}
    
			internal DataColumn Rws_Fld_CodeColumn 
			{
				get 
				{
					return this.columnRws_Fld_Code;
				}
			}
    
			internal DataColumn Rws_Fld_DescribeColumn 
			{
				get 
				{
					return this.columnRws_Fld_Describe;
				}
			}
    
			internal DataColumn Rws_Fld_ufk_StationKindColumn 
			{
				get 
				{
					return this.columnRws_Fld_ufk_StationKind;
				}
			}
    
			internal DataColumn Rws_Fld_StationKindDescribeColumn 
			{
				get 
				{
					return this.columnRws_Fld_StationKindDescribe;
				}
			}
    
			internal DataColumn Rws_Fld_pk_StationColumn 
			{
				get 
				{
					return this.columnRws_Fld_pk_Station;
				}
			}
    
			internal DataColumn Rws_Fld_IsConfirmColumn 
			{
				get 
				{
					return this.columnRws_Fld_IsConfirm;
				}
			}
    
			internal DataColumn Rws_Fld_IsConfirmVirColumn 
			{
				get 
				{
					return this.columnRws_Fld_IsConfirmVir;
				}
			}
    
			internal DataColumn Rws_Fld_FlagColumn 
			{
				get 
				{
					return this.columnRws_Fld_Flag;
				}
			}
    
			public Rws_Sp_Sel_All_NewStationRow this[int index] 
			{
				get 
				{
					return ((Rws_Sp_Sel_All_NewStationRow)(this.Rows[index]));
				}
			}
    
			public event Rws_Sp_Sel_All_NewStationRowChangeEventHandler Rws_Sp_Sel_All_NewStationRowChanged;
    
			public event Rws_Sp_Sel_All_NewStationRowChangeEventHandler Rws_Sp_Sel_All_NewStationRowChanging;
    
			public event Rws_Sp_Sel_All_NewStationRowChangeEventHandler Rws_Sp_Sel_All_NewStationRowDeleted;
    
			public event Rws_Sp_Sel_All_NewStationRowChangeEventHandler Rws_Sp_Sel_All_NewStationRowDeleting;
    
			public void AddRws_Sp_Sel_All_NewStationRow(Rws_Sp_Sel_All_NewStationRow row) 
			{
				this.Rows.Add(row);
			}
    
			public Rws_Sp_Sel_All_NewStationRow AddRws_Sp_Sel_All_NewStationRow(Rws_Sp_Sel_All_RegionRow parentRws_Sp_Sel_All_RegionRowByRws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation, string Rws_Fld_RegionDescribe, short Rws_Fld_Code, string Rws_Fld_Describe, int Rws_Fld_ufk_StationKind, string Rws_Fld_StationKindDescribe, short Rws_Fld_pk_Station, bool Rws_Fld_IsConfirm, bool Rws_Fld_IsConfirmVir, bool Rws_Fld_Flag) 
			{
				Rws_Sp_Sel_All_NewStationRow rowRws_Sp_Sel_All_NewStationRow = ((Rws_Sp_Sel_All_NewStationRow)(this.NewRow()));
				rowRws_Sp_Sel_All_NewStationRow.ItemArray = new object[] {
																				parentRws_Sp_Sel_All_RegionRowByRws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation[0],
																				Rws_Fld_RegionDescribe,
																				Rws_Fld_Code,
																				Rws_Fld_Describe,
																				Rws_Fld_ufk_StationKind,
																				Rws_Fld_StationKindDescribe,
																				Rws_Fld_pk_Station,
																				Rws_Fld_IsConfirm,
																				Rws_Fld_IsConfirmVir,
																				Rws_Fld_Flag};
				this.Rows.Add(rowRws_Sp_Sel_All_NewStationRow);
				return rowRws_Sp_Sel_All_NewStationRow;
			}
    
			public Rws_Sp_Sel_All_NewStationRow FindByRws_Fld_fk_RegionRws_Fld_Code(System.Byte Rws_Fld_fk_Region, short Rws_Fld_Code) 
			{
				return ((Rws_Sp_Sel_All_NewStationRow)(this.Rows.Find(new object[] {
																						Rws_Fld_fk_Region,
																						Rws_Fld_Code})));
			}
    
			public System.Collections.IEnumerator GetEnumerator() 
			{
				return this.Rows.GetEnumerator();
			}
    
			public override DataTable Clone() 
			{
				Rws_Sp_Sel_All_NewStationDataTable cln = ((Rws_Sp_Sel_All_NewStationDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
    
			protected override DataTable CreateInstance() 
			{
				return new Rws_Sp_Sel_All_NewStationDataTable();
			}
    
			internal void InitVars() 
			{
				this.columnRws_Fld_fk_Region = this.Columns["Rws_Fld_fk_Region"];
				this.columnRws_Fld_RegionDescribe = this.Columns["Rws_Fld_RegionDescribe"];
				this.columnRws_Fld_Code = this.Columns["Rws_Fld_Code"];
				this.columnRws_Fld_Describe = this.Columns["Rws_Fld_Describe"];
				this.columnRws_Fld_ufk_StationKind = this.Columns["Rws_Fld_ufk_StationKind"];
				this.columnRws_Fld_StationKindDescribe = this.Columns["Rws_Fld_StationKindDescribe"];
				this.columnRws_Fld_pk_Station = this.Columns["Rws_Fld_pk_Station"];
				this.columnRws_Fld_IsConfirm = this.Columns["Rws_Fld_IsConfirm"];
				this.columnRws_Fld_IsConfirmVir = this.Columns["Rws_Fld_IsConfirmVir"];
				this.columnRws_Fld_Flag = this.Columns["Rws_Fld_Flag"];
			}
    
			private void InitClass() 
			{
				this.columnRws_Fld_fk_Region = new DataColumn("Rws_Fld_fk_Region", typeof(System.Byte), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_fk_Region);
				this.columnRws_Fld_RegionDescribe = new DataColumn("Rws_Fld_RegionDescribe", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_RegionDescribe);
				this.columnRws_Fld_Code = new DataColumn("Rws_Fld_Code", typeof(short), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_Code);
				this.columnRws_Fld_Describe = new DataColumn("Rws_Fld_Describe", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_Describe);
				this.columnRws_Fld_ufk_StationKind = new DataColumn("Rws_Fld_ufk_StationKind", typeof(int), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_ufk_StationKind);
				this.columnRws_Fld_StationKindDescribe = new DataColumn("Rws_Fld_StationKindDescribe", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_StationKindDescribe);
				this.columnRws_Fld_pk_Station = new DataColumn("Rws_Fld_pk_Station", typeof(short), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_pk_Station);
				this.columnRws_Fld_IsConfirm = new DataColumn("Rws_Fld_IsConfirm", typeof(bool), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_IsConfirm);
				this.columnRws_Fld_IsConfirmVir = new DataColumn("Rws_Fld_IsConfirmVir", typeof(bool), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_IsConfirmVir);
				this.columnRws_Fld_Flag = new DataColumn("Rws_Fld_Flag", typeof(bool), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_Flag);
				this.Constraints.Add(new UniqueConstraint("clsDSStationKey1", new DataColumn[] {
																									this.columnRws_Fld_fk_Region,
																									this.columnRws_Fld_Code}, true));
				this.columnRws_Fld_fk_Region.AllowDBNull = false;
				this.columnRws_Fld_RegionDescribe.AllowDBNull = false;
				this.columnRws_Fld_Code.AllowDBNull = false;
				this.columnRws_Fld_Describe.AllowDBNull = false;
				this.columnRws_Fld_ufk_StationKind.AllowDBNull = false;
				this.columnRws_Fld_StationKindDescribe.AllowDBNull = false;
				this.columnRws_Fld_pk_Station.AllowDBNull = false;
				this.columnRws_Fld_IsConfirm.AllowDBNull = false;
				this.columnRws_Fld_IsConfirmVir.AllowDBNull = false;
				this.columnRws_Fld_Flag.AllowDBNull = false;
			}
    
			public Rws_Sp_Sel_All_NewStationRow NewRws_Sp_Sel_All_NewStationRow() 
			{
				return ((Rws_Sp_Sel_All_NewStationRow)(this.NewRow()));
			}
    
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new Rws_Sp_Sel_All_NewStationRow(builder);
			}
    
			protected override System.Type GetRowType() 
			{
				return typeof(Rws_Sp_Sel_All_NewStationRow);
			}
    
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((this.Rws_Sp_Sel_All_NewStationRowChanged != null)) 
				{
					this.Rws_Sp_Sel_All_NewStationRowChanged(this, new Rws_Sp_Sel_All_NewStationRowChangeEvent(((Rws_Sp_Sel_All_NewStationRow)(e.Row)), e.Action));
				}
			}
    
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((this.Rws_Sp_Sel_All_NewStationRowChanging != null)) 
				{
					this.Rws_Sp_Sel_All_NewStationRowChanging(this, new Rws_Sp_Sel_All_NewStationRowChangeEvent(((Rws_Sp_Sel_All_NewStationRow)(e.Row)), e.Action));
				}
			}
    
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((this.Rws_Sp_Sel_All_NewStationRowDeleted != null)) 
				{
					this.Rws_Sp_Sel_All_NewStationRowDeleted(this, new Rws_Sp_Sel_All_NewStationRowChangeEvent(((Rws_Sp_Sel_All_NewStationRow)(e.Row)), e.Action));
				}
			}
    
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((this.Rws_Sp_Sel_All_NewStationRowDeleting != null)) 
				{
					this.Rws_Sp_Sel_All_NewStationRowDeleting(this, new Rws_Sp_Sel_All_NewStationRowChangeEvent(((Rws_Sp_Sel_All_NewStationRow)(e.Row)), e.Action));
				}
			}
    
			public void RemoveRws_Sp_Sel_All_NewStationRow(Rws_Sp_Sel_All_NewStationRow row) 
			{
				this.Rows.Remove(row);
			}
		}

		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_All_NewStationRow : DataRow 
		{
    
			private Rws_Sp_Sel_All_NewStationDataTable tableRws_Sp_Sel_All_NewStation;
    
			internal Rws_Sp_Sel_All_NewStationRow(DataRowBuilder rb) : 
				base(rb) 
			{
				this.tableRws_Sp_Sel_All_NewStation = ((Rws_Sp_Sel_All_NewStationDataTable)(this.Table));
			}
    
			public System.Byte Rws_Fld_fk_Region 
			{
				get 
				{
					return ((System.Byte)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_fk_RegionColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_fk_RegionColumn] = value;
				}
			}
    
			public string Rws_Fld_RegionDescribe 
			{
				get 
				{
					return ((string)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_RegionDescribeColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_RegionDescribeColumn] = value;
				}
			}
    
			public short Rws_Fld_Code 
			{
				get 
				{
					return ((short)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_CodeColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_CodeColumn] = value;
				}
			}
    
			public string Rws_Fld_Describe 
			{
				get 
				{
					return ((string)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_DescribeColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_DescribeColumn] = value;
				}
			}
    
			public int Rws_Fld_ufk_StationKind 
			{
				get 
				{
					return ((int)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_ufk_StationKindColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_ufk_StationKindColumn] = value;
				}
			}
    
			public string Rws_Fld_StationKindDescribe 
			{
				get 
				{
					return ((string)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_StationKindDescribeColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_StationKindDescribeColumn] = value;
				}
			}
    
			public short Rws_Fld_pk_Station 
			{
				get 
				{
					return ((short)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_pk_StationColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_pk_StationColumn] = value;
				}
			}
    
			public bool Rws_Fld_IsConfirm 
			{
				get 
				{
					return ((bool)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_IsConfirmColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_IsConfirmColumn] = value;
				}
			}
    
			public bool Rws_Fld_IsConfirmVir 
			{
				get 
				{
					return ((bool)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_IsConfirmVirColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_IsConfirmVirColumn] = value;
				}
			}
    
			public bool Rws_Fld_Flag 
			{
				get 
				{
					return ((bool)(this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_FlagColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_NewStation.Rws_Fld_FlagColumn] = value;
				}
			}
    
			public Rws_Sp_Sel_All_RegionRow Rws_Sp_Sel_All_RegionRow 
			{
				get 
				{
					return ((Rws_Sp_Sel_All_RegionRow)(this.GetParentRow(this.Table.ParentRelations["Rws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation"])));
				}
				set 
				{
					this.SetParentRow(value, this.Table.ParentRelations["Rws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation"]);
				}
			}
		}

		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_All_NewStationRowChangeEvent : EventArgs 
		{
    
			private Rws_Sp_Sel_All_NewStationRow eventRow;
    
			private DataRowAction eventAction;
    
			public Rws_Sp_Sel_All_NewStationRowChangeEvent(Rws_Sp_Sel_All_NewStationRow row, DataRowAction action) 
			{
				this.eventRow = row;
				this.eventAction = action;
			}
    
			public Rws_Sp_Sel_All_NewStationRow Row 
			{
				get 
				{
					return this.eventRow;
				}
			}
    
			public DataRowAction Action 
			{
				get 
				{
					return this.eventAction;
				}
			}
		}

		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_All_RegionDataTable : DataTable, System.Collections.IEnumerable 
		{
    
			private DataColumn columnRws_Fld_Code;
    
			private DataColumn columnRws_Fld_Describe;
    
			internal Rws_Sp_Sel_All_RegionDataTable() : 
				base("Rws_Sp_Sel_All_Region") 
			{
				this.InitClass();
			}
    
			internal Rws_Sp_Sel_All_RegionDataTable(DataTable table) : 
				base(table.TableName) 
			{
				if ((table.CaseSensitive != table.DataSet.CaseSensitive)) 
				{
					this.CaseSensitive = table.CaseSensitive;
				}
				if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) 
				{
					this.Locale = table.Locale;
				}
				if ((table.Namespace != table.DataSet.Namespace)) 
				{
					this.Namespace = table.Namespace;
				}
				this.Prefix = table.Prefix;
				this.MinimumCapacity = table.MinimumCapacity;
				this.DisplayExpression = table.DisplayExpression;
			}
    
			[System.ComponentModel.Browsable(false)]
			public int Count 
			{
				get 
				{
					return this.Rows.Count;
				}
			}
    
			internal DataColumn Rws_Fld_CodeColumn 
			{
				get 
				{
					return this.columnRws_Fld_Code;
				}
			}
    
			internal DataColumn Rws_Fld_DescribeColumn 
			{
				get 
				{
					return this.columnRws_Fld_Describe;
				}
			}
    
			public Rws_Sp_Sel_All_RegionRow this[int index] 
			{
				get 
				{
					return ((Rws_Sp_Sel_All_RegionRow)(this.Rows[index]));
				}
			}
    
			public event Rws_Sp_Sel_All_RegionRowChangeEventHandler Rws_Sp_Sel_All_RegionRowChanged;
    
			public event Rws_Sp_Sel_All_RegionRowChangeEventHandler Rws_Sp_Sel_All_RegionRowChanging;
    
			public event Rws_Sp_Sel_All_RegionRowChangeEventHandler Rws_Sp_Sel_All_RegionRowDeleted;
    
			public event Rws_Sp_Sel_All_RegionRowChangeEventHandler Rws_Sp_Sel_All_RegionRowDeleting;
    
			public void AddRws_Sp_Sel_All_RegionRow(Rws_Sp_Sel_All_RegionRow row) 
			{
				this.Rows.Add(row);
			}
    
			public Rws_Sp_Sel_All_RegionRow AddRws_Sp_Sel_All_RegionRow(System.Byte Rws_Fld_Code, string Rws_Fld_Describe) 
			{
				Rws_Sp_Sel_All_RegionRow rowRws_Sp_Sel_All_RegionRow = ((Rws_Sp_Sel_All_RegionRow)(this.NewRow()));
				rowRws_Sp_Sel_All_RegionRow.ItemArray = new object[] {
																			Rws_Fld_Code,
																			Rws_Fld_Describe};
				this.Rows.Add(rowRws_Sp_Sel_All_RegionRow);
				return rowRws_Sp_Sel_All_RegionRow;
			}
    
			public Rws_Sp_Sel_All_RegionRow FindByRws_Fld_Code(System.Byte Rws_Fld_Code) 
			{
				return ((Rws_Sp_Sel_All_RegionRow)(this.Rows.Find(new object[] {
																					Rws_Fld_Code})));
			}
    
			public System.Collections.IEnumerator GetEnumerator() 
			{
				return this.Rows.GetEnumerator();
			}
    
			public override DataTable Clone() 
			{
				Rws_Sp_Sel_All_RegionDataTable cln = ((Rws_Sp_Sel_All_RegionDataTable)(base.Clone()));
				cln.InitVars();
				return cln;
			}
    
			protected override DataTable CreateInstance() 
			{
				return new Rws_Sp_Sel_All_RegionDataTable();
			}
    
			internal void InitVars() 
			{
				this.columnRws_Fld_Code = this.Columns["Rws_Fld_Code"];
				this.columnRws_Fld_Describe = this.Columns["Rws_Fld_Describe"];
			}
    
			private void InitClass() 
			{
				this.columnRws_Fld_Code = new DataColumn("Rws_Fld_Code", typeof(System.Byte), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_Code);
				this.columnRws_Fld_Describe = new DataColumn("Rws_Fld_Describe", typeof(string), null, System.Data.MappingType.Element);
				this.Columns.Add(this.columnRws_Fld_Describe);
				this.Constraints.Add(new UniqueConstraint("clsDSStationKey2", new DataColumn[] {
																									this.columnRws_Fld_Code}, true));
				this.columnRws_Fld_Code.AllowDBNull = false;
				this.columnRws_Fld_Code.Unique = true;
				this.columnRws_Fld_Describe.AllowDBNull = false;
			}
    
			public Rws_Sp_Sel_All_RegionRow NewRws_Sp_Sel_All_RegionRow() 
			{
				return ((Rws_Sp_Sel_All_RegionRow)(this.NewRow()));
			}
    
			protected override DataRow NewRowFromBuilder(DataRowBuilder builder) 
			{
				return new Rws_Sp_Sel_All_RegionRow(builder);
			}
    
			protected override System.Type GetRowType() 
			{
				return typeof(Rws_Sp_Sel_All_RegionRow);
			}
    
			protected override void OnRowChanged(DataRowChangeEventArgs e) 
			{
				base.OnRowChanged(e);
				if ((this.Rws_Sp_Sel_All_RegionRowChanged != null)) 
				{
					this.Rws_Sp_Sel_All_RegionRowChanged(this, new Rws_Sp_Sel_All_RegionRowChangeEvent(((Rws_Sp_Sel_All_RegionRow)(e.Row)), e.Action));
				}
			}
    
			protected override void OnRowChanging(DataRowChangeEventArgs e) 
			{
				base.OnRowChanging(e);
				if ((this.Rws_Sp_Sel_All_RegionRowChanging != null)) 
				{
					this.Rws_Sp_Sel_All_RegionRowChanging(this, new Rws_Sp_Sel_All_RegionRowChangeEvent(((Rws_Sp_Sel_All_RegionRow)(e.Row)), e.Action));
				}
			}
    
			protected override void OnRowDeleted(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleted(e);
				if ((this.Rws_Sp_Sel_All_RegionRowDeleted != null)) 
				{
					this.Rws_Sp_Sel_All_RegionRowDeleted(this, new Rws_Sp_Sel_All_RegionRowChangeEvent(((Rws_Sp_Sel_All_RegionRow)(e.Row)), e.Action));
				}
			}
    
			protected override void OnRowDeleting(DataRowChangeEventArgs e) 
			{
				base.OnRowDeleting(e);
				if ((this.Rws_Sp_Sel_All_RegionRowDeleting != null)) 
				{
					this.Rws_Sp_Sel_All_RegionRowDeleting(this, new Rws_Sp_Sel_All_RegionRowChangeEvent(((Rws_Sp_Sel_All_RegionRow)(e.Row)), e.Action));
				}
			}
    
			public void RemoveRws_Sp_Sel_All_RegionRow(Rws_Sp_Sel_All_RegionRow row) 
			{
				this.Rows.Remove(row);
			}
		}

		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_All_RegionRow : DataRow 
		{
    
			private Rws_Sp_Sel_All_RegionDataTable tableRws_Sp_Sel_All_Region;
    
			internal Rws_Sp_Sel_All_RegionRow(DataRowBuilder rb) : 
				base(rb) 
			{
				this.tableRws_Sp_Sel_All_Region = ((Rws_Sp_Sel_All_RegionDataTable)(this.Table));
			}
    
			public System.Byte Rws_Fld_Code 
			{
				get 
				{
					return ((System.Byte)(this[this.tableRws_Sp_Sel_All_Region.Rws_Fld_CodeColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_Region.Rws_Fld_CodeColumn] = value;
				}
			}
    
			public string Rws_Fld_Describe 
			{
				get 
				{
					return ((string)(this[this.tableRws_Sp_Sel_All_Region.Rws_Fld_DescribeColumn]));
				}
				set 
				{
					this[this.tableRws_Sp_Sel_All_Region.Rws_Fld_DescribeColumn] = value;
				}
			}
    
			public Rws_Sp_Sel_All_NewStationRow[] GetRws_Sp_Sel_All_NewStationRows() 
			{
				return ((Rws_Sp_Sel_All_NewStationRow[])(this.GetChildRows(this.Table.ChildRelations["Rws_Sp_Sel_All_RegionRws_Sp_Sel_All_NewStation"])));
			}
		}

		[System.Diagnostics.DebuggerStepThrough()]
			public class Rws_Sp_Sel_All_RegionRowChangeEvent : EventArgs 
		{
    
			private Rws_Sp_Sel_All_RegionRow eventRow;
    
			private DataRowAction eventAction;
    
			public Rws_Sp_Sel_All_RegionRowChangeEvent(Rws_Sp_Sel_All_RegionRow row, DataRowAction action) 
			{
				this.eventRow = row;
				this.eventAction = action;
			}
    
			public Rws_Sp_Sel_All_RegionRow Row 
			{
				get 
				{
					return this.eventRow;
				}
			}
    
			public DataRowAction Action 
			{
				get 
				{
					return this.eventAction;
				}
			}
		}
	}
}
