//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace RWAS.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DS_Rep_AccidentOnRailway")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_Rep_AccidentOnRailway : System.Data.DataSet {
        
        private Rws_Sp_Rep_AccidentOnRailway4DSDataTable tableRws_Sp_Rep_AccidentOnRailway4DS;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_Rep_AccidentOnRailway() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_Rep_AccidentOnRailway(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Rws_Sp_Rep_AccidentOnRailway4DS"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_AccidentOnRailway4DSDataTable(ds.Tables["Rws_Sp_Rep_AccidentOnRailway4DS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Rws_Sp_Rep_AccidentOnRailway4DSDataTable Rws_Sp_Rep_AccidentOnRailway4DS {
            get {
                return this.tableRws_Sp_Rep_AccidentOnRailway4DS;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DS_Rep_AccidentOnRailway cln = ((DS_Rep_AccidentOnRailway)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Rws_Sp_Rep_AccidentOnRailway4DS"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_AccidentOnRailway4DSDataTable(ds.Tables["Rws_Sp_Rep_AccidentOnRailway4DS"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRws_Sp_Rep_AccidentOnRailway4DS = ((Rws_Sp_Rep_AccidentOnRailway4DSDataTable)(base.Tables["Rws_Sp_Rep_AccidentOnRailway4DS"]));
            if ((initTable == true)) {
                if ((this.tableRws_Sp_Rep_AccidentOnRailway4DS != null)) {
                    this.tableRws_Sp_Rep_AccidentOnRailway4DS.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_Rep_AccidentOnRailway";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_Rep_AccidentOnRailway.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRws_Sp_Rep_AccidentOnRailway4DS = new Rws_Sp_Rep_AccidentOnRailway4DSDataTable();
            base.Tables.Add(this.tableRws_Sp_Rep_AccidentOnRailway4DS);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRws_Sp_Rep_AccidentOnRailway4DS() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DS_Rep_AccidentOnRailway ds = new DS_Rep_AccidentOnRailway();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEventHandler(object sender, Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Rws_Sp_Rep_AccidentOnRailway4DSDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnDayDate;
            
            private System.Data.DataColumn columnYearDate;
            
            private System.Data.DataColumn columnRws_Fld_fk_AccidentKind;
            
            private System.Data.DataColumn columnRws_Fld_AccidentKindDescribe;
            
            private System.Data.DataColumn columnRws_Fld_fk_RailWayVehicleKind;
            
            private System.Data.DataColumn columnRws_Fld_RailWayDescribe;
            
            private System.Data.DataColumn columnRailCount;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_AccidentOnRailway4DSDataTable() {
                this.TableName = "Rws_Sp_Rep_AccidentOnRailway4DS";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_AccidentOnRailway4DSDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Rws_Sp_Rep_AccidentOnRailway4DSDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn DayDateColumn {
                get {
                    return this.columnDayDate;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn YearDateColumn {
                get {
                    return this.columnYearDate;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_fk_AccidentKindColumn {
                get {
                    return this.columnRws_Fld_fk_AccidentKind;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentKindDescribeColumn {
                get {
                    return this.columnRws_Fld_AccidentKindDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_fk_RailWayVehicleKindColumn {
                get {
                    return this.columnRws_Fld_fk_RailWayVehicleKind;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_RailWayDescribeColumn {
                get {
                    return this.columnRws_Fld_RailWayDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn RailCountColumn {
                get {
                    return this.columnRailCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_AccidentOnRailway4DSRow this[int index] {
                get {
                    return ((Rws_Sp_Rep_AccidentOnRailway4DSRow)(this.Rows[index]));
                }
            }
            
            public event Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEventHandler Rws_Sp_Rep_AccidentOnRailway4DSRowChanging;
            
            public event Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEventHandler Rws_Sp_Rep_AccidentOnRailway4DSRowChanged;
            
            public event Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEventHandler Rws_Sp_Rep_AccidentOnRailway4DSRowDeleting;
            
            public event Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEventHandler Rws_Sp_Rep_AccidentOnRailway4DSRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRws_Sp_Rep_AccidentOnRailway4DSRow(Rws_Sp_Rep_AccidentOnRailway4DSRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_AccidentOnRailway4DSRow AddRws_Sp_Rep_AccidentOnRailway4DSRow(string DayDate, string YearDate, byte Rws_Fld_fk_AccidentKind, string Rws_Fld_AccidentKindDescribe, byte Rws_Fld_fk_RailWayVehicleKind, string Rws_Fld_RailWayDescribe, int RailCount) {
                Rws_Sp_Rep_AccidentOnRailway4DSRow rowRws_Sp_Rep_AccidentOnRailway4DSRow = ((Rws_Sp_Rep_AccidentOnRailway4DSRow)(this.NewRow()));
                rowRws_Sp_Rep_AccidentOnRailway4DSRow.ItemArray = new object[] {
                        DayDate,
                        YearDate,
                        Rws_Fld_fk_AccidentKind,
                        Rws_Fld_AccidentKindDescribe,
                        Rws_Fld_fk_RailWayVehicleKind,
                        Rws_Fld_RailWayDescribe,
                        RailCount};
                this.Rows.Add(rowRws_Sp_Rep_AccidentOnRailway4DSRow);
                return rowRws_Sp_Rep_AccidentOnRailway4DSRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                Rws_Sp_Rep_AccidentOnRailway4DSDataTable cln = ((Rws_Sp_Rep_AccidentOnRailway4DSDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new Rws_Sp_Rep_AccidentOnRailway4DSDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnDayDate = base.Columns["DayDate"];
                this.columnYearDate = base.Columns["YearDate"];
                this.columnRws_Fld_fk_AccidentKind = base.Columns["Rws_Fld_fk_AccidentKind"];
                this.columnRws_Fld_AccidentKindDescribe = base.Columns["Rws_Fld_AccidentKindDescribe"];
                this.columnRws_Fld_fk_RailWayVehicleKind = base.Columns["Rws_Fld_fk_RailWayVehicleKind"];
                this.columnRws_Fld_RailWayDescribe = base.Columns["Rws_Fld_RailWayDescribe"];
                this.columnRailCount = base.Columns["RailCount"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnDayDate = new System.Data.DataColumn("DayDate", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnDayDate);
                this.columnYearDate = new System.Data.DataColumn("YearDate", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnYearDate);
                this.columnRws_Fld_fk_AccidentKind = new System.Data.DataColumn("Rws_Fld_fk_AccidentKind", typeof(byte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_fk_AccidentKind);
                this.columnRws_Fld_AccidentKindDescribe = new System.Data.DataColumn("Rws_Fld_AccidentKindDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentKindDescribe);
                this.columnRws_Fld_fk_RailWayVehicleKind = new System.Data.DataColumn("Rws_Fld_fk_RailWayVehicleKind", typeof(byte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_fk_RailWayVehicleKind);
                this.columnRws_Fld_RailWayDescribe = new System.Data.DataColumn("Rws_Fld_RailWayDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_RailWayDescribe);
                this.columnRailCount = new System.Data.DataColumn("RailCount", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRailCount);
                this.columnDayDate.ReadOnly = true;
                this.columnRws_Fld_AccidentKindDescribe.AllowDBNull = false;
                this.columnRws_Fld_RailWayDescribe.AllowDBNull = false;
                this.columnRailCount.ReadOnly = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_AccidentOnRailway4DSRow NewRws_Sp_Rep_AccidentOnRailway4DSRow() {
                return ((Rws_Sp_Rep_AccidentOnRailway4DSRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new Rws_Sp_Rep_AccidentOnRailway4DSRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(Rws_Sp_Rep_AccidentOnRailway4DSRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Rws_Sp_Rep_AccidentOnRailway4DSRowChanged != null)) {
                    this.Rws_Sp_Rep_AccidentOnRailway4DSRowChanged(this, new Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent(((Rws_Sp_Rep_AccidentOnRailway4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Rws_Sp_Rep_AccidentOnRailway4DSRowChanging != null)) {
                    this.Rws_Sp_Rep_AccidentOnRailway4DSRowChanging(this, new Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent(((Rws_Sp_Rep_AccidentOnRailway4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Rws_Sp_Rep_AccidentOnRailway4DSRowDeleted != null)) {
                    this.Rws_Sp_Rep_AccidentOnRailway4DSRowDeleted(this, new Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent(((Rws_Sp_Rep_AccidentOnRailway4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Rws_Sp_Rep_AccidentOnRailway4DSRowDeleting != null)) {
                    this.Rws_Sp_Rep_AccidentOnRailway4DSRowDeleting(this, new Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent(((Rws_Sp_Rep_AccidentOnRailway4DSRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRws_Sp_Rep_AccidentOnRailway4DSRow(Rws_Sp_Rep_AccidentOnRailway4DSRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DS_Rep_AccidentOnRailway ds = new DS_Rep_AccidentOnRailway();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Rws_Sp_Rep_AccidentOnRailway4DSDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Rws_Sp_Rep_AccidentOnRailway4DSRow : System.Data.DataRow {
            
            private Rws_Sp_Rep_AccidentOnRailway4DSDataTable tableRws_Sp_Rep_AccidentOnRailway4DS;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_AccidentOnRailway4DSRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRws_Sp_Rep_AccidentOnRailway4DS = ((Rws_Sp_Rep_AccidentOnRailway4DSDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string DayDate {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.DayDateColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'DayDate\' in table \'Rws_Sp_Rep_AccidentOnRailway4DS\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.DayDateColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string YearDate {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.YearDateColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'YearDate\' in table \'Rws_Sp_Rep_AccidentOnRailway4DS\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.YearDateColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Rws_Fld_fk_AccidentKind {
                get {
                    try {
                        return ((byte)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_AccidentKindColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_fk_AccidentKind\' in table \'Rws_Sp_Rep_AccidentOnRai" +
                                "lway4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_AccidentKindColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentKindDescribe {
                get {
                    return ((string)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_AccidentKindDescribeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_AccidentKindDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Rws_Fld_fk_RailWayVehicleKind {
                get {
                    try {
                        return ((byte)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_RailWayVehicleKindColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_fk_RailWayVehicleKind\' in table \'Rws_Sp_Rep_Acciden" +
                                "tOnRailway4DS\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_RailWayVehicleKindColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_RailWayDescribe {
                get {
                    return ((string)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_RailWayDescribeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_RailWayDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int RailCount {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.RailCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'RailCount\' in table \'Rws_Sp_Rep_AccidentOnRailway4DS\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.RailCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsDayDateNull() {
                return this.IsNull(this.tableRws_Sp_Rep_AccidentOnRailway4DS.DayDateColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetDayDateNull() {
                this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.DayDateColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsYearDateNull() {
                return this.IsNull(this.tableRws_Sp_Rep_AccidentOnRailway4DS.YearDateColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetYearDateNull() {
                this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.YearDateColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_fk_AccidentKindNull() {
                return this.IsNull(this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_AccidentKindColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_fk_AccidentKindNull() {
                this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_AccidentKindColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_fk_RailWayVehicleKindNull() {
                return this.IsNull(this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_RailWayVehicleKindColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_fk_RailWayVehicleKindNull() {
                this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.Rws_Fld_fk_RailWayVehicleKindColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRailCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_AccidentOnRailway4DS.RailCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRailCountNull() {
                this[this.tableRws_Sp_Rep_AccidentOnRailway4DS.RailCountColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent : System.EventArgs {
            
            private Rws_Sp_Rep_AccidentOnRailway4DSRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_AccidentOnRailway4DSRowChangeEvent(Rws_Sp_Rep_AccidentOnRailway4DSRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_AccidentOnRailway4DSRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591