//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace RWAS.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DS_Rep_WorkBookPersonelBodilyMentalStatus")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_Rep_WorkBookPersonelBodilyMentalStatus : System.Data.DataSet {
        
        private Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_Rep_WorkBookPersonelBodilyMentalStatus() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_Rep_WorkBookPersonelBodilyMentalStatus(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable(ds.Tables["Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus {
            get {
                return this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DS_Rep_WorkBookPersonelBodilyMentalStatus cln = ((DS_Rep_WorkBookPersonelBodilyMentalStatus)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable(ds.Tables["Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus = ((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable)(base.Tables["Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus"]));
            if ((initTable == true)) {
                if ((this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus != null)) {
                    this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_Rep_WorkBookPersonelBodilyMentalStatus";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_Rep_WorkBookPersonelBodilyMentalStatus.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus = new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable();
            base.Tables.Add(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DS_Rep_WorkBookPersonelBodilyMentalStatus ds = new DS_Rep_WorkBookPersonelBodilyMentalStatus();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEventHandler(object sender, Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnPersonelCount;
            
            private System.Data.DataColumn columnCurrentDate;
            
            private System.Data.DataColumn columnPrs_Fld_UniqueCode;
            
            private System.Data.DataColumn columnPrs_Fld_FirstName;
            
            private System.Data.DataColumn columnPrs_Fld_LastName;
            
            private System.Data.DataColumn columnPrs_Fld_JobDescribe;
            
            private System.Data.DataColumn columnPrs_Fld_RegionDescribe;
            
            private System.Data.DataColumn columnRws_Fld_Row;
            
            private System.Data.DataColumn columnRws_Fld_Description;
            
            private System.Data.DataColumn columnRws_Fld_CheckupDate;
            
            private System.Data.DataColumn columnRws_Fld_HealthKindDescribe;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable() {
                this.TableName = "Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatus";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn PersonelCountColumn {
                get {
                    return this.columnPersonelCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn CurrentDateColumn {
                get {
                    return this.columnCurrentDate;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_UniqueCodeColumn {
                get {
                    return this.columnPrs_Fld_UniqueCode;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_FirstNameColumn {
                get {
                    return this.columnPrs_Fld_FirstName;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_LastNameColumn {
                get {
                    return this.columnPrs_Fld_LastName;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_JobDescribeColumn {
                get {
                    return this.columnPrs_Fld_JobDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_RegionDescribeColumn {
                get {
                    return this.columnPrs_Fld_RegionDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_RowColumn {
                get {
                    return this.columnRws_Fld_Row;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DescriptionColumn {
                get {
                    return this.columnRws_Fld_Description;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_CheckupDateColumn {
                get {
                    return this.columnRws_Fld_CheckupDate;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_HealthKindDescribeColumn {
                get {
                    return this.columnRws_Fld_HealthKindDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow this[int index] {
                get {
                    return ((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(this.Rows[index]));
                }
            }
            
            public event Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEventHandler Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChanging;
            
            public event Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEventHandler Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChanged;
            
            public event Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEventHandler Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowDeleting;
            
            public event Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEventHandler Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow(Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow AddRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow(int PersonelCount, string CurrentDate, int Prs_Fld_UniqueCode, string Prs_Fld_FirstName, string Prs_Fld_LastName, string Prs_Fld_JobDescribe, string Prs_Fld_RegionDescribe, byte Rws_Fld_Row, string Rws_Fld_Description, string Rws_Fld_CheckupDate, string Rws_Fld_HealthKindDescribe) {
                Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow rowRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow = ((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(this.NewRow()));
                rowRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow.ItemArray = new object[] {
                        PersonelCount,
                        CurrentDate,
                        Prs_Fld_UniqueCode,
                        Prs_Fld_FirstName,
                        Prs_Fld_LastName,
                        Prs_Fld_JobDescribe,
                        Prs_Fld_RegionDescribe,
                        Rws_Fld_Row,
                        Rws_Fld_Description,
                        Rws_Fld_CheckupDate,
                        Rws_Fld_HealthKindDescribe};
                this.Rows.Add(rowRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow);
                return rowRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable cln = ((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnPersonelCount = base.Columns["PersonelCount"];
                this.columnCurrentDate = base.Columns["CurrentDate"];
                this.columnPrs_Fld_UniqueCode = base.Columns["Prs_Fld_UniqueCode"];
                this.columnPrs_Fld_FirstName = base.Columns["Prs_Fld_FirstName"];
                this.columnPrs_Fld_LastName = base.Columns["Prs_Fld_LastName"];
                this.columnPrs_Fld_JobDescribe = base.Columns["Prs_Fld_JobDescribe"];
                this.columnPrs_Fld_RegionDescribe = base.Columns["Prs_Fld_RegionDescribe"];
                this.columnRws_Fld_Row = base.Columns["Rws_Fld_Row"];
                this.columnRws_Fld_Description = base.Columns["Rws_Fld_Description"];
                this.columnRws_Fld_CheckupDate = base.Columns["Rws_Fld_CheckupDate"];
                this.columnRws_Fld_HealthKindDescribe = base.Columns["Rws_Fld_HealthKindDescribe"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnPersonelCount = new System.Data.DataColumn("PersonelCount", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPersonelCount);
                this.columnCurrentDate = new System.Data.DataColumn("CurrentDate", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnCurrentDate);
                this.columnPrs_Fld_UniqueCode = new System.Data.DataColumn("Prs_Fld_UniqueCode", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_UniqueCode);
                this.columnPrs_Fld_FirstName = new System.Data.DataColumn("Prs_Fld_FirstName", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_FirstName);
                this.columnPrs_Fld_LastName = new System.Data.DataColumn("Prs_Fld_LastName", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_LastName);
                this.columnPrs_Fld_JobDescribe = new System.Data.DataColumn("Prs_Fld_JobDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_JobDescribe);
                this.columnPrs_Fld_RegionDescribe = new System.Data.DataColumn("Prs_Fld_RegionDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_RegionDescribe);
                this.columnRws_Fld_Row = new System.Data.DataColumn("Rws_Fld_Row", typeof(byte), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Row);
                this.columnRws_Fld_Description = new System.Data.DataColumn("Rws_Fld_Description", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Description);
                this.columnRws_Fld_CheckupDate = new System.Data.DataColumn("Rws_Fld_CheckupDate", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_CheckupDate);
                this.columnRws_Fld_HealthKindDescribe = new System.Data.DataColumn("Rws_Fld_HealthKindDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_HealthKindDescribe);
                this.columnPersonelCount.ReadOnly = true;
                this.columnCurrentDate.ReadOnly = true;
                this.columnPrs_Fld_UniqueCode.AllowDBNull = false;
                this.columnRws_Fld_Row.AllowDBNull = false;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow NewRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow() {
                return ((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChanged != null)) {
                    this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChanged(this, new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent(((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChanging != null)) {
                    this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChanging(this, new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent(((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowDeleted != null)) {
                    this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowDeleted(this, new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent(((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowDeleting != null)) {
                    this.Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowDeleting(this, new Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent(((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow(Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DS_Rep_WorkBookPersonelBodilyMentalStatus ds = new DS_Rep_WorkBookPersonelBodilyMentalStatus();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow : System.Data.DataRow {
            
            private Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus = ((Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int PersonelCount {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.PersonelCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'PersonelCount\' in table \'Rws_Sp_Rep_WorkBookPersonelBodilyM" +
                                "entalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.PersonelCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string CurrentDate {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.CurrentDateColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'CurrentDate\' in table \'Rws_Sp_Rep_WorkBookPersonelBodilyMen" +
                                "talStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.CurrentDateColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Prs_Fld_UniqueCode {
                get {
                    return ((int)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_UniqueCodeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_UniqueCodeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_FirstName {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_FirstNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_FirstName\' in table \'Rws_Sp_Rep_WorkBookPersonelBod" +
                                "ilyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_FirstNameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_LastName {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_LastNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_LastName\' in table \'Rws_Sp_Rep_WorkBookPersonelBodi" +
                                "lyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_LastNameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_JobDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_JobDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_JobDescribe\' in table \'Rws_Sp_Rep_WorkBookPersonelB" +
                                "odilyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_JobDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_RegionDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_RegionDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_RegionDescribe\' in table \'Rws_Sp_Rep_WorkBookPerson" +
                                "elBodilyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_RegionDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte Rws_Fld_Row {
                get {
                    return ((byte)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_RowColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_RowColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_Description {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_DescriptionColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_Description\' in table \'Rws_Sp_Rep_WorkBookPersonelB" +
                                "odilyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_DescriptionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_CheckupDate {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_CheckupDateColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_CheckupDate\' in table \'Rws_Sp_Rep_WorkBookPersonelB" +
                                "odilyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_CheckupDateColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_HealthKindDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_HealthKindDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_HealthKindDescribe\' in table \'Rws_Sp_Rep_WorkBookPe" +
                                "rsonelBodilyMentalStatus\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_HealthKindDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPersonelCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.PersonelCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPersonelCountNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.PersonelCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsCurrentDateNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.CurrentDateColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetCurrentDateNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.CurrentDateColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_FirstNameNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_FirstNameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_FirstNameNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_FirstNameColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_LastNameNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_LastNameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_LastNameNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_LastNameColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_JobDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_JobDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_JobDescribeNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_JobDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_RegionDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_RegionDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_RegionDescribeNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Prs_Fld_RegionDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DescriptionNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_DescriptionColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DescriptionNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_DescriptionColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_CheckupDateNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_CheckupDateColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_CheckupDateNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_CheckupDateColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_HealthKindDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_HealthKindDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_HealthKindDescribeNull() {
                this[this.tableRws_Sp_Rep_WorkBookPersonelBodilyMentalStatus.Rws_Fld_HealthKindDescribeColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent : System.EventArgs {
            
            private Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRowChangeEvent(Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_WorkBookPersonelBodilyMentalStatusRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591