//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace RWAS.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DS_Report2")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_Report2 : System.Data.DataSet {
        
        private Rws_Sp_Rep_Report2DataTable tableRws_Sp_Rep_Report2;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_Report2() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_Report2(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Rws_Sp_Rep_Report2"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_Report2DataTable(ds.Tables["Rws_Sp_Rep_Report2"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Rws_Sp_Rep_Report2DataTable Rws_Sp_Rep_Report2 {
            get {
                return this.tableRws_Sp_Rep_Report2;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DS_Report2 cln = ((DS_Report2)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Rws_Sp_Rep_Report2"] != null)) {
                    base.Tables.Add(new Rws_Sp_Rep_Report2DataTable(ds.Tables["Rws_Sp_Rep_Report2"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableRws_Sp_Rep_Report2 = ((Rws_Sp_Rep_Report2DataTable)(base.Tables["Rws_Sp_Rep_Report2"]));
            if ((initTable == true)) {
                if ((this.tableRws_Sp_Rep_Report2 != null)) {
                    this.tableRws_Sp_Rep_Report2.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_Report2";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_Report2.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableRws_Sp_Rep_Report2 = new Rws_Sp_Rep_Report2DataTable();
            base.Tables.Add(this.tableRws_Sp_Rep_Report2);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeRws_Sp_Rep_Report2() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DS_Report2 ds = new DS_Report2();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void Rws_Sp_Rep_Report2RowChangeEventHandler(object sender, Rws_Sp_Rep_Report2RowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Rws_Sp_Rep_Report2DataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnRws_Fld_FileCategorize;
            
            private System.Data.DataColumn columnRws_Fld_AccidentDate;
            
            private System.Data.DataColumn columnRws_Fld_AccidentTime;
            
            private System.Data.DataColumn columnRws_Fld_RegionDescribe;
            
            private System.Data.DataColumn columnRws_Fld_AccidentLocation;
            
            private System.Data.DataColumn columnRws_Fld_Kilometer;
            
            private System.Data.DataColumn columnRws_Fld_AccidentTelGraph;
            
            private System.Data.DataColumn columnRws_Fld_BlockTime;
            
            private System.Data.DataColumn columnRws_Fld_AccidentDegreeDescribe;
            
            private System.Data.DataColumn columnRws_Fld_TrainNo;
            
            private System.Data.DataColumn columnRws_Fld_SerialNo;
            
            private System.Data.DataColumn columnRws_Fld_WagonCount;
            
            private System.Data.DataColumn columnRws_Fld_TrainWeight;
            
            private System.Data.DataColumn columnPrs_Fld_TrainBossName;
            
            private System.Data.DataColumn columnPrs_Fld_LocoDriverName;
            
            private System.Data.DataColumn columnRws_Fld_RailWayVehicleKindDescribe;
            
            private System.Data.DataColumn columnRws_Fld_fk_SerialNo;
            
            private System.Data.DataColumn columnRws_Fld_IsOnManeuver;
            
            private System.Data.DataColumn columnRws_Fld_DeletedPassengerTrainCount;
            
            private System.Data.DataColumn columnRws_Fld_DeletedCarrierTrainCount;
            
            private System.Data.DataColumn columnRws_Fld_DeletedOtherTrainCount;
            
            private System.Data.DataColumn columnRws_Fld_DelayTimePassengerTrainCount;
            
            private System.Data.DataColumn columnRws_Fld_DelayTimeCarrierTrainCount;
            
            private System.Data.DataColumn columnRws_Fld_DelayTimeOtherTrainCount;
            
            private System.Data.DataColumn columnRws_Fld_AccidentKindDescribe;
            
            private System.Data.DataColumn columnRws_Fld_Det_EarlyAccidentReasonDescribe;
            
            private System.Data.DataColumn columnRws_Fld_AccidentEffectiveDescribe;
            
            private System.Data.DataColumn columnRws_Fld_RailWayAfoulCount;
            
            private System.Data.DataColumn columnRws_Fld_PassengerAfoulCount;
            
            private System.Data.DataColumn columnRws_Fld_RailWayDieCount;
            
            private System.Data.DataColumn columnRws_Fld_PassengerDieCount;
            
            private System.Data.DataColumn columnRws_Fld_PassengerGender;
            
            private System.Data.DataColumn columnRws_Fld_ufk_PassengerAgeStatuse;
            
            private System.Data.DataColumn columnRws_Fld_ufk_CrossroadKind;
            
            private System.Data.DataColumn columnRws_Fld_Det_EarlyAccidentReasonDescription;
            
            private System.Data.DataColumn columnRws_Fld_ufk_RoadVehicleKind;
            
            private System.Data.DataColumn columnRws_Fld_Description;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_Report2DataTable() {
                this.TableName = "Rws_Sp_Rep_Report2";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_Report2DataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Rws_Sp_Rep_Report2DataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_FileCategorizeColumn {
                get {
                    return this.columnRws_Fld_FileCategorize;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentDateColumn {
                get {
                    return this.columnRws_Fld_AccidentDate;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentTimeColumn {
                get {
                    return this.columnRws_Fld_AccidentTime;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_RegionDescribeColumn {
                get {
                    return this.columnRws_Fld_RegionDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentLocationColumn {
                get {
                    return this.columnRws_Fld_AccidentLocation;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_KilometerColumn {
                get {
                    return this.columnRws_Fld_Kilometer;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentTelGraphColumn {
                get {
                    return this.columnRws_Fld_AccidentTelGraph;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_BlockTimeColumn {
                get {
                    return this.columnRws_Fld_BlockTime;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentDegreeDescribeColumn {
                get {
                    return this.columnRws_Fld_AccidentDegreeDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_TrainNoColumn {
                get {
                    return this.columnRws_Fld_TrainNo;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_SerialNoColumn {
                get {
                    return this.columnRws_Fld_SerialNo;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_WagonCountColumn {
                get {
                    return this.columnRws_Fld_WagonCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_TrainWeightColumn {
                get {
                    return this.columnRws_Fld_TrainWeight;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_TrainBossNameColumn {
                get {
                    return this.columnPrs_Fld_TrainBossName;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_LocoDriverNameColumn {
                get {
                    return this.columnPrs_Fld_LocoDriverName;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_RailWayVehicleKindDescribeColumn {
                get {
                    return this.columnRws_Fld_RailWayVehicleKindDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_fk_SerialNoColumn {
                get {
                    return this.columnRws_Fld_fk_SerialNo;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_IsOnManeuverColumn {
                get {
                    return this.columnRws_Fld_IsOnManeuver;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DeletedPassengerTrainCountColumn {
                get {
                    return this.columnRws_Fld_DeletedPassengerTrainCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DeletedCarrierTrainCountColumn {
                get {
                    return this.columnRws_Fld_DeletedCarrierTrainCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DeletedOtherTrainCountColumn {
                get {
                    return this.columnRws_Fld_DeletedOtherTrainCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DelayTimePassengerTrainCountColumn {
                get {
                    return this.columnRws_Fld_DelayTimePassengerTrainCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DelayTimeCarrierTrainCountColumn {
                get {
                    return this.columnRws_Fld_DelayTimeCarrierTrainCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DelayTimeOtherTrainCountColumn {
                get {
                    return this.columnRws_Fld_DelayTimeOtherTrainCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentKindDescribeColumn {
                get {
                    return this.columnRws_Fld_AccidentKindDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_Det_EarlyAccidentReasonDescribeColumn {
                get {
                    return this.columnRws_Fld_Det_EarlyAccidentReasonDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_AccidentEffectiveDescribeColumn {
                get {
                    return this.columnRws_Fld_AccidentEffectiveDescribe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_RailWayAfoulCountColumn {
                get {
                    return this.columnRws_Fld_RailWayAfoulCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_PassengerAfoulCountColumn {
                get {
                    return this.columnRws_Fld_PassengerAfoulCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_RailWayDieCountColumn {
                get {
                    return this.columnRws_Fld_RailWayDieCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_PassengerDieCountColumn {
                get {
                    return this.columnRws_Fld_PassengerDieCount;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_PassengerGenderColumn {
                get {
                    return this.columnRws_Fld_PassengerGender;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_ufk_PassengerAgeStatuseColumn {
                get {
                    return this.columnRws_Fld_ufk_PassengerAgeStatuse;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_ufk_CrossroadKindColumn {
                get {
                    return this.columnRws_Fld_ufk_CrossroadKind;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_Det_EarlyAccidentReasonDescriptionColumn {
                get {
                    return this.columnRws_Fld_Det_EarlyAccidentReasonDescription;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_ufk_RoadVehicleKindColumn {
                get {
                    return this.columnRws_Fld_ufk_RoadVehicleKind;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Rws_Fld_DescriptionColumn {
                get {
                    return this.columnRws_Fld_Description;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_Report2Row this[int index] {
                get {
                    return ((Rws_Sp_Rep_Report2Row)(this.Rows[index]));
                }
            }
            
            public event Rws_Sp_Rep_Report2RowChangeEventHandler Rws_Sp_Rep_Report2RowChanging;
            
            public event Rws_Sp_Rep_Report2RowChangeEventHandler Rws_Sp_Rep_Report2RowChanged;
            
            public event Rws_Sp_Rep_Report2RowChangeEventHandler Rws_Sp_Rep_Report2RowDeleting;
            
            public event Rws_Sp_Rep_Report2RowChangeEventHandler Rws_Sp_Rep_Report2RowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddRws_Sp_Rep_Report2Row(Rws_Sp_Rep_Report2Row row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_Report2Row AddRws_Sp_Rep_Report2Row(
                        string Rws_Fld_FileCategorize, 
                        string Rws_Fld_AccidentDate, 
                        string Rws_Fld_AccidentTime, 
                        string Rws_Fld_RegionDescribe, 
                        string Rws_Fld_AccidentLocation, 
                        string Rws_Fld_Kilometer, 
                        string Rws_Fld_AccidentTelGraph, 
                        string Rws_Fld_BlockTime, 
                        string Rws_Fld_AccidentDegreeDescribe, 
                        int Rws_Fld_TrainNo, 
                        string Rws_Fld_SerialNo, 
                        short Rws_Fld_WagonCount, 
                        short Rws_Fld_TrainWeight, 
                        string Prs_Fld_TrainBossName, 
                        string Prs_Fld_LocoDriverName, 
                        string Rws_Fld_RailWayVehicleKindDescribe, 
                        string Rws_Fld_fk_SerialNo, 
                        string Rws_Fld_IsOnManeuver, 
                        short Rws_Fld_DeletedPassengerTrainCount, 
                        short Rws_Fld_DeletedCarrierTrainCount, 
                        short Rws_Fld_DeletedOtherTrainCount, 
                        short Rws_Fld_DelayTimePassengerTrainCount, 
                        short Rws_Fld_DelayTimeCarrierTrainCount, 
                        short Rws_Fld_DelayTimeOtherTrainCount, 
                        string Rws_Fld_AccidentKindDescribe, 
                        string Rws_Fld_Det_EarlyAccidentReasonDescribe, 
                        string Rws_Fld_AccidentEffectiveDescribe, 
                        short Rws_Fld_RailWayAfoulCount, 
                        short Rws_Fld_PassengerAfoulCount, 
                        short Rws_Fld_RailWayDieCount, 
                        short Rws_Fld_PassengerDieCount, 
                        string Rws_Fld_PassengerGender, 
                        string Rws_Fld_ufk_PassengerAgeStatuse, 
                        string Rws_Fld_ufk_CrossroadKind, 
                        string Rws_Fld_Det_EarlyAccidentReasonDescription, 
                        string Rws_Fld_ufk_RoadVehicleKind, 
                        string Rws_Fld_Description) {
                Rws_Sp_Rep_Report2Row rowRws_Sp_Rep_Report2Row = ((Rws_Sp_Rep_Report2Row)(this.NewRow()));
                rowRws_Sp_Rep_Report2Row.ItemArray = new object[] {
                        Rws_Fld_FileCategorize,
                        Rws_Fld_AccidentDate,
                        Rws_Fld_AccidentTime,
                        Rws_Fld_RegionDescribe,
                        Rws_Fld_AccidentLocation,
                        Rws_Fld_Kilometer,
                        Rws_Fld_AccidentTelGraph,
                        Rws_Fld_BlockTime,
                        Rws_Fld_AccidentDegreeDescribe,
                        Rws_Fld_TrainNo,
                        Rws_Fld_SerialNo,
                        Rws_Fld_WagonCount,
                        Rws_Fld_TrainWeight,
                        Prs_Fld_TrainBossName,
                        Prs_Fld_LocoDriverName,
                        Rws_Fld_RailWayVehicleKindDescribe,
                        Rws_Fld_fk_SerialNo,
                        Rws_Fld_IsOnManeuver,
                        Rws_Fld_DeletedPassengerTrainCount,
                        Rws_Fld_DeletedCarrierTrainCount,
                        Rws_Fld_DeletedOtherTrainCount,
                        Rws_Fld_DelayTimePassengerTrainCount,
                        Rws_Fld_DelayTimeCarrierTrainCount,
                        Rws_Fld_DelayTimeOtherTrainCount,
                        Rws_Fld_AccidentKindDescribe,
                        Rws_Fld_Det_EarlyAccidentReasonDescribe,
                        Rws_Fld_AccidentEffectiveDescribe,
                        Rws_Fld_RailWayAfoulCount,
                        Rws_Fld_PassengerAfoulCount,
                        Rws_Fld_RailWayDieCount,
                        Rws_Fld_PassengerDieCount,
                        Rws_Fld_PassengerGender,
                        Rws_Fld_ufk_PassengerAgeStatuse,
                        Rws_Fld_ufk_CrossroadKind,
                        Rws_Fld_Det_EarlyAccidentReasonDescription,
                        Rws_Fld_ufk_RoadVehicleKind,
                        Rws_Fld_Description};
                this.Rows.Add(rowRws_Sp_Rep_Report2Row);
                return rowRws_Sp_Rep_Report2Row;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                Rws_Sp_Rep_Report2DataTable cln = ((Rws_Sp_Rep_Report2DataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new Rws_Sp_Rep_Report2DataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnRws_Fld_FileCategorize = base.Columns["Rws_Fld_FileCategorize"];
                this.columnRws_Fld_AccidentDate = base.Columns["Rws_Fld_AccidentDate"];
                this.columnRws_Fld_AccidentTime = base.Columns["Rws_Fld_AccidentTime"];
                this.columnRws_Fld_RegionDescribe = base.Columns["Rws_Fld_RegionDescribe"];
                this.columnRws_Fld_AccidentLocation = base.Columns["Rws_Fld_AccidentLocation"];
                this.columnRws_Fld_Kilometer = base.Columns["Rws_Fld_Kilometer"];
                this.columnRws_Fld_AccidentTelGraph = base.Columns["Rws_Fld_AccidentTelGraph"];
                this.columnRws_Fld_BlockTime = base.Columns["Rws_Fld_BlockTime"];
                this.columnRws_Fld_AccidentDegreeDescribe = base.Columns["Rws_Fld_AccidentDegreeDescribe"];
                this.columnRws_Fld_TrainNo = base.Columns["Rws_Fld_TrainNo"];
                this.columnRws_Fld_SerialNo = base.Columns["Rws_Fld_SerialNo"];
                this.columnRws_Fld_WagonCount = base.Columns["Rws_Fld_WagonCount"];
                this.columnRws_Fld_TrainWeight = base.Columns["Rws_Fld_TrainWeight"];
                this.columnPrs_Fld_TrainBossName = base.Columns["Prs_Fld_TrainBossName"];
                this.columnPrs_Fld_LocoDriverName = base.Columns["Prs_Fld_LocoDriverName"];
                this.columnRws_Fld_RailWayVehicleKindDescribe = base.Columns["Rws_Fld_RailWayVehicleKindDescribe"];
                this.columnRws_Fld_fk_SerialNo = base.Columns["Rws_Fld_fk_SerialNo"];
                this.columnRws_Fld_IsOnManeuver = base.Columns["Rws_Fld_IsOnManeuver"];
                this.columnRws_Fld_DeletedPassengerTrainCount = base.Columns["Rws_Fld_DeletedPassengerTrainCount"];
                this.columnRws_Fld_DeletedCarrierTrainCount = base.Columns["Rws_Fld_DeletedCarrierTrainCount"];
                this.columnRws_Fld_DeletedOtherTrainCount = base.Columns["Rws_Fld_DeletedOtherTrainCount"];
                this.columnRws_Fld_DelayTimePassengerTrainCount = base.Columns["Rws_Fld_DelayTimePassengerTrainCount"];
                this.columnRws_Fld_DelayTimeCarrierTrainCount = base.Columns["Rws_Fld_DelayTimeCarrierTrainCount"];
                this.columnRws_Fld_DelayTimeOtherTrainCount = base.Columns["Rws_Fld_DelayTimeOtherTrainCount"];
                this.columnRws_Fld_AccidentKindDescribe = base.Columns["Rws_Fld_AccidentKindDescribe"];
                this.columnRws_Fld_Det_EarlyAccidentReasonDescribe = base.Columns["Rws_Fld_Det_EarlyAccidentReasonDescribe"];
                this.columnRws_Fld_AccidentEffectiveDescribe = base.Columns["Rws_Fld_AccidentEffectiveDescribe"];
                this.columnRws_Fld_RailWayAfoulCount = base.Columns["Rws_Fld_RailWayAfoulCount"];
                this.columnRws_Fld_PassengerAfoulCount = base.Columns["Rws_Fld_PassengerAfoulCount"];
                this.columnRws_Fld_RailWayDieCount = base.Columns["Rws_Fld_RailWayDieCount"];
                this.columnRws_Fld_PassengerDieCount = base.Columns["Rws_Fld_PassengerDieCount"];
                this.columnRws_Fld_PassengerGender = base.Columns["Rws_Fld_PassengerGender"];
                this.columnRws_Fld_ufk_PassengerAgeStatuse = base.Columns["Rws_Fld_ufk_PassengerAgeStatuse"];
                this.columnRws_Fld_ufk_CrossroadKind = base.Columns["Rws_Fld_ufk_CrossroadKind"];
                this.columnRws_Fld_Det_EarlyAccidentReasonDescription = base.Columns["Rws_Fld_Det_EarlyAccidentReasonDescription"];
                this.columnRws_Fld_ufk_RoadVehicleKind = base.Columns["Rws_Fld_ufk_RoadVehicleKind"];
                this.columnRws_Fld_Description = base.Columns["Rws_Fld_Description"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnRws_Fld_FileCategorize = new System.Data.DataColumn("Rws_Fld_FileCategorize", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_FileCategorize);
                this.columnRws_Fld_AccidentDate = new System.Data.DataColumn("Rws_Fld_AccidentDate", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentDate);
                this.columnRws_Fld_AccidentTime = new System.Data.DataColumn("Rws_Fld_AccidentTime", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentTime);
                this.columnRws_Fld_RegionDescribe = new System.Data.DataColumn("Rws_Fld_RegionDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_RegionDescribe);
                this.columnRws_Fld_AccidentLocation = new System.Data.DataColumn("Rws_Fld_AccidentLocation", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentLocation);
                this.columnRws_Fld_Kilometer = new System.Data.DataColumn("Rws_Fld_Kilometer", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Kilometer);
                this.columnRws_Fld_AccidentTelGraph = new System.Data.DataColumn("Rws_Fld_AccidentTelGraph", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentTelGraph);
                this.columnRws_Fld_BlockTime = new System.Data.DataColumn("Rws_Fld_BlockTime", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_BlockTime);
                this.columnRws_Fld_AccidentDegreeDescribe = new System.Data.DataColumn("Rws_Fld_AccidentDegreeDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentDegreeDescribe);
                this.columnRws_Fld_TrainNo = new System.Data.DataColumn("Rws_Fld_TrainNo", typeof(int), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_TrainNo);
                this.columnRws_Fld_SerialNo = new System.Data.DataColumn("Rws_Fld_SerialNo", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_SerialNo);
                this.columnRws_Fld_WagonCount = new System.Data.DataColumn("Rws_Fld_WagonCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_WagonCount);
                this.columnRws_Fld_TrainWeight = new System.Data.DataColumn("Rws_Fld_TrainWeight", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_TrainWeight);
                this.columnPrs_Fld_TrainBossName = new System.Data.DataColumn("Prs_Fld_TrainBossName", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_TrainBossName);
                this.columnPrs_Fld_LocoDriverName = new System.Data.DataColumn("Prs_Fld_LocoDriverName", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_LocoDriverName);
                this.columnRws_Fld_RailWayVehicleKindDescribe = new System.Data.DataColumn("Rws_Fld_RailWayVehicleKindDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_RailWayVehicleKindDescribe);
                this.columnRws_Fld_fk_SerialNo = new System.Data.DataColumn("Rws_Fld_fk_SerialNo", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_fk_SerialNo);
                this.columnRws_Fld_IsOnManeuver = new System.Data.DataColumn("Rws_Fld_IsOnManeuver", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_IsOnManeuver);
                this.columnRws_Fld_DeletedPassengerTrainCount = new System.Data.DataColumn("Rws_Fld_DeletedPassengerTrainCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_DeletedPassengerTrainCount);
                this.columnRws_Fld_DeletedCarrierTrainCount = new System.Data.DataColumn("Rws_Fld_DeletedCarrierTrainCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_DeletedCarrierTrainCount);
                this.columnRws_Fld_DeletedOtherTrainCount = new System.Data.DataColumn("Rws_Fld_DeletedOtherTrainCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_DeletedOtherTrainCount);
                this.columnRws_Fld_DelayTimePassengerTrainCount = new System.Data.DataColumn("Rws_Fld_DelayTimePassengerTrainCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_DelayTimePassengerTrainCount);
                this.columnRws_Fld_DelayTimeCarrierTrainCount = new System.Data.DataColumn("Rws_Fld_DelayTimeCarrierTrainCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_DelayTimeCarrierTrainCount);
                this.columnRws_Fld_DelayTimeOtherTrainCount = new System.Data.DataColumn("Rws_Fld_DelayTimeOtherTrainCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_DelayTimeOtherTrainCount);
                this.columnRws_Fld_AccidentKindDescribe = new System.Data.DataColumn("Rws_Fld_AccidentKindDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentKindDescribe);
                this.columnRws_Fld_Det_EarlyAccidentReasonDescribe = new System.Data.DataColumn("Rws_Fld_Det_EarlyAccidentReasonDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Det_EarlyAccidentReasonDescribe);
                this.columnRws_Fld_AccidentEffectiveDescribe = new System.Data.DataColumn("Rws_Fld_AccidentEffectiveDescribe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_AccidentEffectiveDescribe);
                this.columnRws_Fld_RailWayAfoulCount = new System.Data.DataColumn("Rws_Fld_RailWayAfoulCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_RailWayAfoulCount);
                this.columnRws_Fld_PassengerAfoulCount = new System.Data.DataColumn("Rws_Fld_PassengerAfoulCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_PassengerAfoulCount);
                this.columnRws_Fld_RailWayDieCount = new System.Data.DataColumn("Rws_Fld_RailWayDieCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_RailWayDieCount);
                this.columnRws_Fld_PassengerDieCount = new System.Data.DataColumn("Rws_Fld_PassengerDieCount", typeof(short), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_PassengerDieCount);
                this.columnRws_Fld_PassengerGender = new System.Data.DataColumn("Rws_Fld_PassengerGender", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_PassengerGender);
                this.columnRws_Fld_ufk_PassengerAgeStatuse = new System.Data.DataColumn("Rws_Fld_ufk_PassengerAgeStatuse", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_ufk_PassengerAgeStatuse);
                this.columnRws_Fld_ufk_CrossroadKind = new System.Data.DataColumn("Rws_Fld_ufk_CrossroadKind", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_ufk_CrossroadKind);
                this.columnRws_Fld_Det_EarlyAccidentReasonDescription = new System.Data.DataColumn("Rws_Fld_Det_EarlyAccidentReasonDescription", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Det_EarlyAccidentReasonDescription);
                this.columnRws_Fld_ufk_RoadVehicleKind = new System.Data.DataColumn("Rws_Fld_ufk_RoadVehicleKind", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_ufk_RoadVehicleKind);
                this.columnRws_Fld_Description = new System.Data.DataColumn("Rws_Fld_Description", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnRws_Fld_Description);
                this.columnRws_Fld_FileCategorize.AllowDBNull = false;
                this.columnRws_Fld_AccidentDate.ReadOnly = true;
                this.columnRws_Fld_AccidentTime.ReadOnly = true;
                this.columnRws_Fld_RegionDescribe.AllowDBNull = false;
                this.columnRws_Fld_AccidentLocation.ReadOnly = true;
                this.columnRws_Fld_Kilometer.ReadOnly = true;
                this.columnPrs_Fld_TrainBossName.ReadOnly = true;
                this.columnPrs_Fld_LocoDriverName.ReadOnly = true;
                this.columnRws_Fld_IsOnManeuver.ReadOnly = true;
                this.columnRws_Fld_PassengerGender.ReadOnly = true;
                this.columnRws_Fld_ufk_PassengerAgeStatuse.ReadOnly = true;
                this.columnRws_Fld_ufk_CrossroadKind.ReadOnly = true;
                this.columnRws_Fld_ufk_RoadVehicleKind.ReadOnly = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_Report2Row NewRws_Sp_Rep_Report2Row() {
                return ((Rws_Sp_Rep_Report2Row)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new Rws_Sp_Rep_Report2Row(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(Rws_Sp_Rep_Report2Row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Rws_Sp_Rep_Report2RowChanged != null)) {
                    this.Rws_Sp_Rep_Report2RowChanged(this, new Rws_Sp_Rep_Report2RowChangeEvent(((Rws_Sp_Rep_Report2Row)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Rws_Sp_Rep_Report2RowChanging != null)) {
                    this.Rws_Sp_Rep_Report2RowChanging(this, new Rws_Sp_Rep_Report2RowChangeEvent(((Rws_Sp_Rep_Report2Row)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Rws_Sp_Rep_Report2RowDeleted != null)) {
                    this.Rws_Sp_Rep_Report2RowDeleted(this, new Rws_Sp_Rep_Report2RowChangeEvent(((Rws_Sp_Rep_Report2Row)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Rws_Sp_Rep_Report2RowDeleting != null)) {
                    this.Rws_Sp_Rep_Report2RowDeleting(this, new Rws_Sp_Rep_Report2RowChangeEvent(((Rws_Sp_Rep_Report2Row)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveRws_Sp_Rep_Report2Row(Rws_Sp_Rep_Report2Row row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DS_Report2 ds = new DS_Report2();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Rws_Sp_Rep_Report2DataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Rws_Sp_Rep_Report2Row : System.Data.DataRow {
            
            private Rws_Sp_Rep_Report2DataTable tableRws_Sp_Rep_Report2;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Rws_Sp_Rep_Report2Row(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableRws_Sp_Rep_Report2 = ((Rws_Sp_Rep_Report2DataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_FileCategorize {
                get {
                    return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_FileCategorizeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_FileCategorizeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentDate {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDateColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentDate\' in table \'Rws_Sp_Rep_Report2\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDateColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentTime {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTimeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentTime\' in table \'Rws_Sp_Rep_Report2\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTimeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_RegionDescribe {
                get {
                    return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RegionDescribeColumn]));
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RegionDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentLocation {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentLocationColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentLocation\' in table \'Rws_Sp_Rep_Report2\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentLocationColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_Kilometer {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_KilometerColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_Kilometer\' in table \'Rws_Sp_Rep_Report2\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_KilometerColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentTelGraph {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTelGraphColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentTelGraph\' in table \'Rws_Sp_Rep_Report2\' is " +
                                "DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTelGraphColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_BlockTime {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_BlockTimeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_BlockTime\' in table \'Rws_Sp_Rep_Report2\' is DBNull." +
                                "", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_BlockTimeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentDegreeDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDegreeDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentDegreeDescribe\' in table \'Rws_Sp_Rep_Report" +
                                "2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDegreeDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int Rws_Fld_TrainNo {
                get {
                    try {
                        return ((int)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainNoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_TrainNo\' in table \'Rws_Sp_Rep_Report2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainNoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_SerialNo {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_SerialNoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_SerialNo\' in table \'Rws_Sp_Rep_Report2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_SerialNoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_WagonCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_WagonCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_WagonCount\' in table \'Rws_Sp_Rep_Report2\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_WagonCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_TrainWeight {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainWeightColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_TrainWeight\' in table \'Rws_Sp_Rep_Report2\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainWeightColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_TrainBossName {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Prs_Fld_TrainBossNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_TrainBossName\' in table \'Rws_Sp_Rep_Report2\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Prs_Fld_TrainBossNameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_LocoDriverName {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Prs_Fld_LocoDriverNameColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_LocoDriverName\' in table \'Rws_Sp_Rep_Report2\' is DB" +
                                "Null.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Prs_Fld_LocoDriverNameColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_RailWayVehicleKindDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayVehicleKindDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_RailWayVehicleKindDescribe\' in table \'Rws_Sp_Rep_Re" +
                                "port2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayVehicleKindDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_fk_SerialNo {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_fk_SerialNoColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_fk_SerialNo\' in table \'Rws_Sp_Rep_Report2\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_fk_SerialNoColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_IsOnManeuver {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_IsOnManeuverColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_IsOnManeuver\' in table \'Rws_Sp_Rep_Report2\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_IsOnManeuverColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_DeletedPassengerTrainCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedPassengerTrainCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_DeletedPassengerTrainCount\' in table \'Rws_Sp_Rep_Re" +
                                "port2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedPassengerTrainCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_DeletedCarrierTrainCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedCarrierTrainCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_DeletedCarrierTrainCount\' in table \'Rws_Sp_Rep_Repo" +
                                "rt2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedCarrierTrainCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_DeletedOtherTrainCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedOtherTrainCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_DeletedOtherTrainCount\' in table \'Rws_Sp_Rep_Report" +
                                "2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedOtherTrainCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_DelayTimePassengerTrainCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimePassengerTrainCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_DelayTimePassengerTrainCount\' in table \'Rws_Sp_Rep_" +
                                "Report2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimePassengerTrainCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_DelayTimeCarrierTrainCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeCarrierTrainCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_DelayTimeCarrierTrainCount\' in table \'Rws_Sp_Rep_Re" +
                                "port2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeCarrierTrainCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_DelayTimeOtherTrainCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeOtherTrainCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_DelayTimeOtherTrainCount\' in table \'Rws_Sp_Rep_Repo" +
                                "rt2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeOtherTrainCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentKindDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentKindDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentKindDescribe\' in table \'Rws_Sp_Rep_Report2\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentKindDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_Det_EarlyAccidentReasonDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_Det_EarlyAccidentReasonDescribe\' in table \'Rws_Sp_R" +
                                "ep_Report2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_AccidentEffectiveDescribe {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentEffectiveDescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_AccidentEffectiveDescribe\' in table \'Rws_Sp_Rep_Rep" +
                                "ort2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentEffectiveDescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_RailWayAfoulCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayAfoulCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_RailWayAfoulCount\' in table \'Rws_Sp_Rep_Report2\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayAfoulCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_PassengerAfoulCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerAfoulCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_PassengerAfoulCount\' in table \'Rws_Sp_Rep_Report2\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerAfoulCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_RailWayDieCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayDieCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_RailWayDieCount\' in table \'Rws_Sp_Rep_Report2\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayDieCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short Rws_Fld_PassengerDieCount {
                get {
                    try {
                        return ((short)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerDieCountColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_PassengerDieCount\' in table \'Rws_Sp_Rep_Report2\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerDieCountColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_PassengerGender {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerGenderColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_PassengerGender\' in table \'Rws_Sp_Rep_Report2\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerGenderColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_ufk_PassengerAgeStatuse {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_PassengerAgeStatuseColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_ufk_PassengerAgeStatuse\' in table \'Rws_Sp_Rep_Repor" +
                                "t2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_PassengerAgeStatuseColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_ufk_CrossroadKind {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_CrossroadKindColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_ufk_CrossroadKind\' in table \'Rws_Sp_Rep_Report2\' is" +
                                " DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_CrossroadKindColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_Det_EarlyAccidentReasonDescription {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescriptionColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_Det_EarlyAccidentReasonDescription\' in table \'Rws_S" +
                                "p_Rep_Report2\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescriptionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_ufk_RoadVehicleKind {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_RoadVehicleKindColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_ufk_RoadVehicleKind\' in table \'Rws_Sp_Rep_Report2\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_RoadVehicleKindColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Rws_Fld_Description {
                get {
                    try {
                        return ((string)(this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DescriptionColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Rws_Fld_Description\' in table \'Rws_Sp_Rep_Report2\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DescriptionColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentDateNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDateColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentDateNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDateColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentTimeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTimeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentTimeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTimeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentLocationNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentLocationColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentLocationNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentLocationColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_KilometerNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_KilometerColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_KilometerNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_KilometerColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentTelGraphNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTelGraphColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentTelGraphNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentTelGraphColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_BlockTimeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_BlockTimeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_BlockTimeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_BlockTimeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentDegreeDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDegreeDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentDegreeDescribeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentDegreeDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_TrainNoNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainNoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_TrainNoNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainNoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_SerialNoNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_SerialNoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_SerialNoNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_SerialNoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_WagonCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_WagonCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_WagonCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_WagonCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_TrainWeightNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainWeightColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_TrainWeightNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_TrainWeightColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_TrainBossNameNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Prs_Fld_TrainBossNameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_TrainBossNameNull() {
                this[this.tableRws_Sp_Rep_Report2.Prs_Fld_TrainBossNameColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_LocoDriverNameNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Prs_Fld_LocoDriverNameColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_LocoDriverNameNull() {
                this[this.tableRws_Sp_Rep_Report2.Prs_Fld_LocoDriverNameColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_RailWayVehicleKindDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayVehicleKindDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_RailWayVehicleKindDescribeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayVehicleKindDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_fk_SerialNoNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_fk_SerialNoColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_fk_SerialNoNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_fk_SerialNoColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_IsOnManeuverNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_IsOnManeuverColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_IsOnManeuverNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_IsOnManeuverColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DeletedPassengerTrainCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedPassengerTrainCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DeletedPassengerTrainCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedPassengerTrainCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DeletedCarrierTrainCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedCarrierTrainCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DeletedCarrierTrainCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedCarrierTrainCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DeletedOtherTrainCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedOtherTrainCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DeletedOtherTrainCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DeletedOtherTrainCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DelayTimePassengerTrainCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimePassengerTrainCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DelayTimePassengerTrainCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimePassengerTrainCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DelayTimeCarrierTrainCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeCarrierTrainCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DelayTimeCarrierTrainCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeCarrierTrainCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DelayTimeOtherTrainCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeOtherTrainCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DelayTimeOtherTrainCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DelayTimeOtherTrainCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentKindDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentKindDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentKindDescribeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentKindDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_Det_EarlyAccidentReasonDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_Det_EarlyAccidentReasonDescribeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_AccidentEffectiveDescribeNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentEffectiveDescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_AccidentEffectiveDescribeNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_AccidentEffectiveDescribeColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_RailWayAfoulCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayAfoulCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_RailWayAfoulCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayAfoulCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_PassengerAfoulCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerAfoulCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_PassengerAfoulCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerAfoulCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_RailWayDieCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayDieCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_RailWayDieCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_RailWayDieCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_PassengerDieCountNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerDieCountColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_PassengerDieCountNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerDieCountColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_PassengerGenderNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerGenderColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_PassengerGenderNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_PassengerGenderColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_ufk_PassengerAgeStatuseNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_PassengerAgeStatuseColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_ufk_PassengerAgeStatuseNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_PassengerAgeStatuseColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_ufk_CrossroadKindNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_CrossroadKindColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_ufk_CrossroadKindNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_CrossroadKindColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_Det_EarlyAccidentReasonDescriptionNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescriptionColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_Det_EarlyAccidentReasonDescriptionNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_Det_EarlyAccidentReasonDescriptionColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_ufk_RoadVehicleKindNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_RoadVehicleKindColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_ufk_RoadVehicleKindNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_ufk_RoadVehicleKindColumn] = System.Convert.DBNull;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsRws_Fld_DescriptionNull() {
                return this.IsNull(this.tableRws_Sp_Rep_Report2.Rws_Fld_DescriptionColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetRws_Fld_DescriptionNull() {
                this[this.tableRws_Sp_Rep_Report2.Rws_Fld_DescriptionColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Rws_Sp_Rep_Report2RowChangeEvent : System.EventArgs {
            
            private Rws_Sp_Rep_Report2Row eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_Report2RowChangeEvent(Rws_Sp_Rep_Report2Row row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Rws_Sp_Rep_Report2Row Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591