//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShakelliReportsUI.DataLayer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppObject
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AppObject()
        {
            this.AppGroupUserObject = new HashSet<AppGroupUserObject>();
            this.AppObject1 = new HashSet<AppObject>();
        }
    
        public int ObjectId { get; set; }
        public string ObjectName { get; set; }
        public string ObjectDs { get; set; }
        public Nullable<int> ParentObjectId { get; set; }
        public Nullable<int> ObjectTypeCode { get; set; }
        public string StoredProcedure { get; set; }
        public string UrlPath { get; set; }
        public bool HasDirectPath { get; set; }
        public bool HasOwnGrid { get; set; }
        public bool HasServerReport { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppGroupUserObject> AppGroupUserObject { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AppObject> AppObject1 { get; set; }
        public virtual AppObject AppObject2 { get; set; }
    }
}
