//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace RWAS.Common {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [Serializable()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.ComponentModel.ToolboxItem(true)]
    [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [System.Xml.Serialization.XmlRootAttribute("DS_Job")]
    [System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class DS_Job : System.Data.DataSet {
        
        private Prs_Sp_Sel_All_JobDataTable tablePrs_Sp_Sel_All_Job;
        
        private System.Data.SchemaSerializationMode _schemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public DS_Job() {
            this.BeginInit();
            this.InitClass();
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected DS_Job(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
                if ((ds.Tables["Prs_Sp_Sel_All_Job"] != null)) {
                    base.Tables.Add(new Prs_Sp_Sel_All_JobDataTable(ds.Tables["Prs_Sp_Sel_All_Job"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new System.Xml.XmlTextReader(new System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.Browsable(false)]
        [System.ComponentModel.DesignerSerializationVisibility(System.ComponentModel.DesignerSerializationVisibility.Content)]
        public Prs_Sp_Sel_All_JobDataTable Prs_Sp_Sel_All_Job {
            get {
                return this.tablePrs_Sp_Sel_All_Job;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.BrowsableAttribute(true)]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [System.ComponentModel.DesignerSerializationVisibilityAttribute(System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override System.Data.DataSet Clone() {
            DS_Job cln = ((DS_Job)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                System.Data.DataSet ds = new System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["Prs_Sp_Sel_All_Job"] != null)) {
                    base.Tables.Add(new Prs_Sp_Sel_All_JobDataTable(ds.Tables["Prs_Sp_Sel_All_Job"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            System.IO.MemoryStream stream = new System.IO.MemoryStream();
            this.WriteXmlSchema(new System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return System.Xml.Schema.XmlSchema.Read(new System.Xml.XmlTextReader(stream), null);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tablePrs_Sp_Sel_All_Job = ((Prs_Sp_Sel_All_JobDataTable)(base.Tables["Prs_Sp_Sel_All_Job"]));
            if ((initTable == true)) {
                if ((this.tablePrs_Sp_Sel_All_Job != null)) {
                    this.tablePrs_Sp_Sel_All_Job.InitVars();
                }
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "DS_Job";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/DS_Job.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = System.Data.SchemaSerializationMode.IncludeSchema;
            this.tablePrs_Sp_Sel_All_Job = new Prs_Sp_Sel_All_JobDataTable();
            base.Tables.Add(this.tablePrs_Sp_Sel_All_Job);
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializePrs_Sp_Sel_All_Job() {
            return false;
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(System.Xml.Schema.XmlSchemaSet xs) {
            DS_Job ds = new DS_Job();
            System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
            System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
            xs.Add(ds.GetSchemaSerializable());
            System.Xml.Schema.XmlSchemaAny any = new System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            return type;
        }
        
        public delegate void Prs_Sp_Sel_All_JobRowChangeEventHandler(object sender, Prs_Sp_Sel_All_JobRowChangeEvent e);
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [System.Serializable()]
        [System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class Prs_Sp_Sel_All_JobDataTable : System.Data.DataTable, System.Collections.IEnumerable {
            
            private System.Data.DataColumn columnPrs_Fld_Code;
            
            private System.Data.DataColumn columnPrs_Fld_Describe;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobDataTable() {
                this.TableName = "Prs_Sp_Sel_All_Job";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Prs_Sp_Sel_All_JobDataTable(System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected Prs_Sp_Sel_All_JobDataTable(System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_CodeColumn {
                get {
                    return this.columnPrs_Fld_Code;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataColumn Prs_Fld_DescribeColumn {
                get {
                    return this.columnPrs_Fld_Describe;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobRow this[int index] {
                get {
                    return ((Prs_Sp_Sel_All_JobRow)(this.Rows[index]));
                }
            }
            
            public event Prs_Sp_Sel_All_JobRowChangeEventHandler Prs_Sp_Sel_All_JobRowChanging;
            
            public event Prs_Sp_Sel_All_JobRowChangeEventHandler Prs_Sp_Sel_All_JobRowChanged;
            
            public event Prs_Sp_Sel_All_JobRowChangeEventHandler Prs_Sp_Sel_All_JobRowDeleting;
            
            public event Prs_Sp_Sel_All_JobRowChangeEventHandler Prs_Sp_Sel_All_JobRowDeleted;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddPrs_Sp_Sel_All_JobRow(Prs_Sp_Sel_All_JobRow row) {
                this.Rows.Add(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobRow AddPrs_Sp_Sel_All_JobRow(string Prs_Fld_Code, string Prs_Fld_Describe) {
                Prs_Sp_Sel_All_JobRow rowPrs_Sp_Sel_All_JobRow = ((Prs_Sp_Sel_All_JobRow)(this.NewRow()));
                rowPrs_Sp_Sel_All_JobRow.ItemArray = new object[] {
                        Prs_Fld_Code,
                        Prs_Fld_Describe};
                this.Rows.Add(rowPrs_Sp_Sel_All_JobRow);
                return rowPrs_Sp_Sel_All_JobRow;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobRow FindByPrs_Fld_Code(string Prs_Fld_Code) {
                return ((Prs_Sp_Sel_All_JobRow)(this.Rows.Find(new object[] {
                            Prs_Fld_Code})));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public virtual System.Collections.IEnumerator GetEnumerator() {
                return this.Rows.GetEnumerator();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override System.Data.DataTable Clone() {
                Prs_Sp_Sel_All_JobDataTable cln = ((Prs_Sp_Sel_All_JobDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataTable CreateInstance() {
                return new Prs_Sp_Sel_All_JobDataTable();
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnPrs_Fld_Code = base.Columns["Prs_Fld_Code"];
                this.columnPrs_Fld_Describe = base.Columns["Prs_Fld_Describe"];
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnPrs_Fld_Code = new System.Data.DataColumn("Prs_Fld_Code", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_Code);
                this.columnPrs_Fld_Describe = new System.Data.DataColumn("Prs_Fld_Describe", typeof(string), null, System.Data.MappingType.Element);
                base.Columns.Add(this.columnPrs_Fld_Describe);
                this.Constraints.Add(new System.Data.UniqueConstraint("DS_JobKey1", new System.Data.DataColumn[] {
                                this.columnPrs_Fld_Code}, true));
                this.columnPrs_Fld_Code.AllowDBNull = false;
                this.columnPrs_Fld_Code.Unique = true;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobRow NewPrs_Sp_Sel_All_JobRow() {
                return ((Prs_Sp_Sel_All_JobRow)(this.NewRow()));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Data.DataRow NewRowFromBuilder(System.Data.DataRowBuilder builder) {
                return new Prs_Sp_Sel_All_JobRow(builder);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override System.Type GetRowType() {
                return typeof(Prs_Sp_Sel_All_JobRow);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.Prs_Sp_Sel_All_JobRowChanged != null)) {
                    this.Prs_Sp_Sel_All_JobRowChanged(this, new Prs_Sp_Sel_All_JobRowChangeEvent(((Prs_Sp_Sel_All_JobRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.Prs_Sp_Sel_All_JobRowChanging != null)) {
                    this.Prs_Sp_Sel_All_JobRowChanging(this, new Prs_Sp_Sel_All_JobRowChangeEvent(((Prs_Sp_Sel_All_JobRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.Prs_Sp_Sel_All_JobRowDeleted != null)) {
                    this.Prs_Sp_Sel_All_JobRowDeleted(this, new Prs_Sp_Sel_All_JobRowChangeEvent(((Prs_Sp_Sel_All_JobRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.Prs_Sp_Sel_All_JobRowDeleting != null)) {
                    this.Prs_Sp_Sel_All_JobRowDeleting(this, new Prs_Sp_Sel_All_JobRowChangeEvent(((Prs_Sp_Sel_All_JobRow)(e.Row)), e.Action));
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemovePrs_Sp_Sel_All_JobRow(Prs_Sp_Sel_All_JobRow row) {
                this.Rows.Remove(row);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(System.Xml.Schema.XmlSchemaSet xs) {
                System.Xml.Schema.XmlSchemaComplexType type = new System.Xml.Schema.XmlSchemaComplexType();
                System.Xml.Schema.XmlSchemaSequence sequence = new System.Xml.Schema.XmlSchemaSequence();
                DS_Job ds = new DS_Job();
                xs.Add(ds.GetSchemaSerializable());
                System.Xml.Schema.XmlSchemaAny any1 = new System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                System.Xml.Schema.XmlSchemaAny any2 = new System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                System.Xml.Schema.XmlSchemaAttribute attribute1 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                System.Xml.Schema.XmlSchemaAttribute attribute2 = new System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "Prs_Sp_Sel_All_JobDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                return type;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class Prs_Sp_Sel_All_JobRow : System.Data.DataRow {
            
            private Prs_Sp_Sel_All_JobDataTable tablePrs_Sp_Sel_All_Job;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal Prs_Sp_Sel_All_JobRow(System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tablePrs_Sp_Sel_All_Job = ((Prs_Sp_Sel_All_JobDataTable)(this.Table));
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_Code {
                get {
                    return ((string)(this[this.tablePrs_Sp_Sel_All_Job.Prs_Fld_CodeColumn]));
                }
                set {
                    this[this.tablePrs_Sp_Sel_All_Job.Prs_Fld_CodeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string Prs_Fld_Describe {
                get {
                    try {
                        return ((string)(this[this.tablePrs_Sp_Sel_All_Job.Prs_Fld_DescribeColumn]));
                    }
                    catch (System.InvalidCastException e) {
                        throw new System.Data.StrongTypingException("The value for column \'Prs_Fld_Describe\' in table \'Prs_Sp_Sel_All_Job\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tablePrs_Sp_Sel_All_Job.Prs_Fld_DescribeColumn] = value;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsPrs_Fld_DescribeNull() {
                return this.IsNull(this.tablePrs_Sp_Sel_All_Job.Prs_Fld_DescribeColumn);
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetPrs_Fld_DescribeNull() {
                this[this.tablePrs_Sp_Sel_All_Job.Prs_Fld_DescribeColumn] = System.Convert.DBNull;
            }
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class Prs_Sp_Sel_All_JobRowChangeEvent : System.EventArgs {
            
            private Prs_Sp_Sel_All_JobRow eventRow;
            
            private System.Data.DataRowAction eventAction;
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobRowChangeEvent(Prs_Sp_Sel_All_JobRow row, System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public Prs_Sp_Sel_All_JobRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}

#pragma warning restore 1591